import { describe, expect, it } from "vitest";

import {
  decodeMetadataPatchSummary,
  decodeRedactedOptionSummary,
  describeRedactedOptionSummary,
  isRedactedOptionSummary,
} from "./redactedArguments";
import { redactedArguments } from "@/test/redactedArgumentFixture";

// Two kinds of test live in this file, and the distinction is the point.
//
// LIVE PATH: the input comes from src/test/fixtures/redacted-tool-arguments.json,
// which is generated by calling the real Python redactor. These assert what
// the decoder does with payloads the producer genuinely emits.
//
// DEFENSIVE: the input is hand-built because the producer cannot be made to
// emit it through these tools (pydantic rejects a non-mapping `patch` before
// redaction runs, so `<invalid-options>` is unreachable here). These assert
// only that the decoder fails closed. They are labelled so nobody later reads
// them as evidence about the producer — presenting an unreachable shape as
// real is the defect this fixture exists to prevent.

describe("decodeRedactedOptionSummary (live path)", () => {
  it("decodes the shape summary the redactor puts in patch_node_options.patch", () => {
    const args = redactedArguments("patch_node_options_mixed_shapes");

    expect(decodeRedactedOptionSummary(args.patch)).toEqual({
      rootShape: "mapping",
      entryCount: 4,
      shapeCounts: { mapping: 1, scalar: 2, sequence: 1, set: 0 },
    });
  });

  it("decodes an empty patch as a zero entry count, not as an absent summary", () => {
    const args = redactedArguments("patch_node_options_empty_patch");

    expect(decodeRedactedOptionSummary(args.patch)).toEqual({
      rootShape: "mapping",
      entryCount: 0,
      shapeCounts: { mapping: 0, scalar: 0, sequence: 0, set: 0 },
    });
  });

  it("decodes the same grammar on the source and output patch tools", () => {
    expect(
      decodeRedactedOptionSummary(redactedArguments("patch_source_options_two_scalars").patch),
    ).toMatchObject({ entryCount: 2, shapeCounts: { scalar: 2 } });
    expect(
      decodeRedactedOptionSummary(redactedArguments("patch_output_options_one_scalar").patch),
    ).toMatchObject({ entryCount: 1, shapeCounts: { scalar: 1 } });
  });

  it("decodes the `options` argument of the non-patch mutating tools too", () => {
    // Same summarizer, different argument name — set_source, upsert_node,
    // set_output and set_pipeline all route `options` through it.
    expect(
      decodeRedactedOptionSummary(redactedArguments("upsert_node_with_options").options),
    ).toMatchObject({ rootShape: "mapping", entryCount: 1 });
    expect(
      decodeRedactedOptionSummary(redactedArguments("set_output_with_options").options),
    ).toMatchObject({ rootShape: "mapping", entryCount: 1 });
  });

  it("recognises a nested set_pipeline options summary through isRedactedOptionSummary", () => {
    const args = redactedArguments("set_pipeline_replaying_current_state");
    const nodes = args.nodes as Array<Record<string, unknown>>;

    expect(isRedactedOptionSummary(nodes[0].options)).toBe(true);
    // The identity-bearing keys are NOT summaries and must stay comparable.
    expect(isRedactedOptionSummary(nodes[0].id)).toBe(false);
    expect(isRedactedOptionSummary(nodes[0].plugin)).toBe(false);
    expect(isRedactedOptionSummary(nodes[0].on_success)).toBe(false);
  });
});

describe("decodeRedactedOptionSummary (defensive: shapes the tools cannot emit)", () => {
  it("returns null for a raw options object", () => {
    // The pre-redaction shape. Reading it as a summary is the original bug;
    // reading it as valid data would be the same bug inverted.
    expect(decodeRedactedOptionSummary({ path: "in.csv" })).toBeNull();
  });

  it("returns null for the producer's non-mapping marker, which is a JSON string", () => {
    // `_summarize_set_source_options` emits json.dumps("<invalid-options>"),
    // so it parses to text rather than to an object.
    expect(decodeRedactedOptionSummary('"<invalid-options>"')).toBeNull();
  });

  it("returns null for text that is not JSON at all", () => {
    expect(decodeRedactedOptionSummary("not json")).toBeNull();
    expect(decodeRedactedOptionSummary("")).toBeNull();
  });

  it("returns null when the grammar is present but malformed", () => {
    const counts = { mapping: 0, scalar: 1, sequence: 0, set: 0 };
    // Unknown root shape class.
    expect(
      decodeRedactedOptionSummary(
        JSON.stringify({ _option_shape: "tuple", entry_count: 1, value_shape_counts: counts }),
      ),
    ).toBeNull();
    // Missing a class from the closed vocabulary.
    expect(
      decodeRedactedOptionSummary(
        JSON.stringify({
          _option_shape: "mapping",
          entry_count: 1,
          value_shape_counts: { mapping: 0, scalar: 1, sequence: 0 },
        }),
      ),
    ).toBeNull();
    // Counts must be non-negative integers.
    expect(
      decodeRedactedOptionSummary(
        JSON.stringify({ _option_shape: "mapping", entry_count: -1, value_shape_counts: counts }),
      ),
    ).toBeNull();
    expect(
      decodeRedactedOptionSummary(
        JSON.stringify({ _option_shape: "mapping", entry_count: 1.5, value_shape_counts: counts }),
      ),
    ).toBeNull();
  });

  it("returns null for non-string inputs", () => {
    expect(decodeRedactedOptionSummary(null)).toBeNull();
    expect(decodeRedactedOptionSummary(undefined)).toBeNull();
    expect(decodeRedactedOptionSummary(42)).toBeNull();
    expect(decodeRedactedOptionSummary(["a"])).toBeNull();
  });
});

describe("describeRedactedOptionSummary", () => {
  it("counts entries in the payload and says the contents are gone", () => {
    const summary = decodeRedactedOptionSummary(
      redactedArguments("patch_node_options_mixed_shapes").patch,
    );

    expect(summary).not.toBeNull();
    expect(describeRedactedOptionSummary(summary!)).toBe(
      "4 entries, keys and values redacted",
    );
  });

  it("uses the singular for one entry", () => {
    const summary = decodeRedactedOptionSummary(
      redactedArguments("patch_node_options_one_mapping").patch,
    );

    expect(describeRedactedOptionSummary(summary!)).toBe("1 entry, keys and values redacted");
  });

  it("says 'no entries' rather than claiming redacted content that is not there", () => {
    const summary = decodeRedactedOptionSummary(
      redactedArguments("patch_node_options_empty_patch").patch,
    );

    expect(describeRedactedOptionSummary(summary!)).toBe("no entries");
  });
});

describe("decodeMetadataPatchSummary (live path)", () => {
  it("decodes both recognised keys from the sentinel", () => {
    const args = redactedArguments("set_metadata_name_and_description");

    expect(decodeMetadataPatchSummary(args.patch)).toEqual({
      kind: "keys",
      keys: ["description", "name"],
      touchesUnknownField: false,
    });
  });

  it("decodes a single-key patch", () => {
    const args = redactedArguments("set_metadata_name_only");

    expect(decodeMetadataPatchSummary(args.patch)).toEqual({
      kind: "keys",
      keys: ["name"],
      touchesUnknownField: false,
    });
  });

  it("reports an unrecognised field alongside the keys it can name", () => {
    const args = redactedArguments("set_metadata_unknown_key");

    expect(decodeMetadataPatchSummary(args.patch)).toEqual({
      kind: "keys",
      keys: ["name"],
      touchesUnknownField: true,
    });
  });

  it("distinguishes an empty patch from an unreadable one", () => {
    // empty → a projection exists and reports nothing.
    expect(decodeMetadataPatchSummary(redactedArguments("set_metadata_empty").patch)).toEqual({
      kind: "empty",
    });
    // invalid → no honest projection at all; the caller must fall back.
    expect(
      decodeMetadataPatchSummary(redactedArguments("set_metadata_invalid").patch),
    ).toBeNull();
  });
});

describe("decodeMetadataPatchSummary (defensive: shapes the tool cannot emit)", () => {
  it("returns null for a raw patch object", () => {
    expect(decodeMetadataPatchSummary({ name: "Renamed" })).toBeNull();
  });

  it("returns null for a token outside the closed vocabulary", () => {
    expect(decodeMetadataPatchSummary("<metadata-patch:owner>")).toBeNull();
    expect(decodeMetadataPatchSummary("<metadata-patch:name,owner>")).toBeNull();
  });

  it("returns null for a malformed sentinel", () => {
    expect(decodeMetadataPatchSummary("<metadata-patch:>")).toBeNull();
    expect(decodeMetadataPatchSummary("<metadata-patch:name")).toBeNull();
    expect(decodeMetadataPatchSummary("metadata-patch:name>")).toBeNull();
    expect(decodeMetadataPatchSummary("")).toBeNull();
  });

  it("accepts the tokens in any order, since order carries no meaning", () => {
    expect(decodeMetadataPatchSummary("<metadata-patch:name,description>")).toEqual({
      kind: "keys",
      keys: ["description", "name"],
      touchesUnknownField: false,
    });
  });

  it("returns null for non-string inputs", () => {
    expect(decodeMetadataPatchSummary(null)).toBeNull();
    expect(decodeMetadataPatchSummary(undefined)).toBeNull();
    expect(decodeMetadataPatchSummary(7)).toBeNull();
  });
});
