"""Shared contracts and pure helpers for AWS ECS acceptance."""

from __future__ import annotations

import contextlib
import hashlib
import json
import re
import typing
import uuid
from collections.abc import Iterator, Mapping
from contextvars import ContextVar
from dataclasses import dataclass
from datetime import UTC, datetime
from urllib.parse import urlsplit

from pydantic import BaseModel

from elspeth.web.config import WebSettings

_MAX_IDENTITY_CHARS = 128
_EVIDENCE_KINDS = (
    "web-log",
    "doctor-log",
    "deployment-event",
    "task-definition",
    "terraform-plan",
    "terraform-destroy-plan",
)
EVIDENCE_KINDS = _EVIDENCE_KINDS
CONNECT_TIMEOUT_SECONDS = 5.0
READ_TIMEOUT_SECONDS = 15.0
WRITE_TIMEOUT_SECONDS = 10.0
POOL_TIMEOUT_SECONDS = 5.0
MAX_JSON_RESPONSE_BYTES = 1024 * 1024
MAX_BLOB_RESPONSE_BYTES = 8 * 1024 * 1024
RUN_POLL_DEADLINE_SECONDS = 5 * 60
RUN_POLL_INTERVAL_SECONDS = 1.0
MAX_STATE_FILE_BYTES = 64 * 1024
MAX_EXEC_RECEIPT_CHARS = 16 * 1024
MAX_EXEC_STREAM_BYTES = 2 * 1024 * 1024
MAX_CONTROL_DOCUMENT_BYTES = 256 * 1024
_EMERGENCY_CLEANUP_SECONDS = 3 * 60 * 60
_LOOPBACK_HOSTS = frozenset({"127.0.0.1", "::1", "localhost"})
_SHA256_PATTERN = re.compile(r"[0-9a-f]{64}\Z")
_GIT_SHA_PATTERN = re.compile(r"(?:[0-9a-f]{40}|[0-9a-f]{64})\Z")
# `artifacts.artifact_id` (elspeth.core.landscape.schema) is a
# ``String(64)`` column, NOT a UUID column, and is never generated by
# ``uuid.uuid4()``: the sink-effect producer path (the only live producer,
# ``elspeth.core.landscape.execution.sink_effect_finalization``) derives it
# via a labeled SHA-256 digest (64 lowercase hex chars); the legacy
# ``core.ids.generate_id()`` default is a bare ``uuid4().hex`` (32 lowercase
# hex chars, no dashes). Neither shape is a canonical dashed UUID, unlike
# session/blob/run/landscape-run identities (all genuine
# ``str(uuid.uuid4())`` DB values elsewhere in the web layer). Only the two
# live producer widths are valid.
_ARTIFACT_ID_PATTERN = re.compile(r"(?:[0-9a-f]{32}|[0-9a-f]{64})\Z")
_SCENARIO_ID_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}\Z")
_TERMINAL_RUN_STATUSES = frozenset({"completed", "completed_with_failures", "failed", "empty", "cancelled"})
FORBIDDEN_AWS_OVERRIDE_ENV = frozenset(
    {
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_SESSION_TOKEN",
        "AWS_SECURITY_TOKEN",
        "AWS_CREDENTIAL_EXPIRATION",
        "AWS_PROFILE",
        "AWS_DEFAULT_PROFILE",
        "AWS_CONFIG_FILE",
        "AWS_SHARED_CREDENTIALS_FILE",
        "AWS_CREDENTIAL_FILE",
        "BOTO_CONFIG",
        "AWS_ENDPOINT_URL",
        "AWS_ENDPOINT_URL_S3",
        "AWS_ENDPOINT_URL_BEDROCK",
        "AWS_ENDPOINT_URL_BEDROCK_RUNTIME",
        "AWS_ENDPOINT_URL_CLOUDWATCH",
        "AWS_ENDPOINT_URL_XRAY",
        "AWS_EC2_METADATA_SERVICE_ENDPOINT",
        "AWS_ROLE_ARN",
        "AWS_WEB_IDENTITY_TOKEN_FILE",
        "AWS_ROLE_SESSION_NAME",
        "AWS_CONTAINER_CREDENTIALS_FULL_URI",
        "AWS_CONTAINER_AUTHORIZATION_TOKEN",
        "AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE",
    }
)
SCENARIO_ASSIGNMENT_NAMES = (
    "ACTIVE_SCENARIO_ID",
    "ACCEPTANCE_RUN_ID",
    "DEPLOYMENT_MODE",
    "TARGET_PLATFORM",
    "AWS_REGION",
    "ECS_CLUSTER",
    "ECS_SERVICE",
    "WEB_CONTAINER_NAME",
    "ELSPETH_WEB__DATA_DIR",
    "ELSPETH_WEB__PAYLOAD_STORE_PATH",
    "ELSPETH_WEB__COMPOSER_MODEL",
    "ELSPETH_WEB__COMPOSER_ADVISOR_MODEL",
    "ELSPETH_WEB__PLUGIN_ALLOWLIST",
    "ELSPETH_WEB__PLUGIN_PREFERENCES",
    "ELSPETH_WEB__PLUGIN_CONTROL_MODES",
    "ELSPETH_WEB__LLM_PROFILES",
    "ELSPETH_WEB__DEFAULT_LLM_PROFILE",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_PROFILES",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_DEFAULT_PROFILES",
    "ELSPETH_ACCEPTANCE_PLUGIN_POLICY_BINDING_SHA256",
    "ELSPETH_BEDROCK_LIVE_TEST_MODEL",
    "CLOUDWATCH_AGENT_IMAGE",
    "CLOUDWATCH_AGENT_CONFIG_JSON_SHA256",
    "CLOUDWATCH_AGENT_OTEL_YAML_SHA256",
    "TARGET_GROUP_ARN",
    "ALB_BASE_URL",
    "ALB_ARN",
    "CANDIDATE_TASK_DEFINITION",
    "DOCTOR_TASK_DEFINITION",
    "DOCTOR_CONTAINER_NAME",
    "DOCTOR_NETWORK_CONFIGURATION",
    "PAYLOAD_VERIFIER_TASK_DEFINITION",
    "LOCAL_AUTH_VERIFIER_TASK_DEFINITION",
    "ROLLBACK_DOCTOR_TASK_DEFINITION",
    "WEB_LOG_GROUP",
    "WEB_LOG_STREAM_PREFIX",
    "DOCTOR_LOG_GROUP",
    "DOCTOR_LOG_STREAM_PREFIX",
    "OPERATOR_METRICS_LOG_GROUP",
    "ECS_DEPLOYMENT_EVENT_RULE",
    "ECS_DEPLOYMENT_EVENT_TARGET_ID",
    "ECS_DEPLOYMENT_EVENT_LOG_GROUP",
    "PREVIOUS_TASK_DEFINITION",
    "FIRST_DEPLOY_LISTENER_RULE_ARN",
    "FIRST_DEPLOY_FORWARD_ACTIONS",
    "FIRST_DEPLOY_DISABLED_ACTIONS",
    "COGNITO_USER_POOL_ID",
    "DB_CLUSTER_IDENTIFIER",
    "ELSPETH_TEST_S3_BUCKET",
    "OIDC_EXPECTED_ISSUER",
    "OIDC_EXPECTED_AUDIENCE",
    "OIDC_EXPECTED_AUTHORIZATION_ORIGIN",
    "OIDC_EXPECTED_AUDIENCE_CLAIM",
    "SCENARIO_TF_DIR",
    "SCENARIO_TF_VARS",
    "SCENARIO_TF_BINDING_SHA",
    "SCENARIO_TF_BINDING_FILE",
)
SCENARIO_VALUE_FIELDS = frozenset(SCENARIO_ASSIGNMENT_NAMES[2:])
_SCENARIO_VALUE_FIELDS = SCENARIO_VALUE_FIELDS
PLUGIN_POLICY_ASSIGNMENT_NAMES = (
    "ELSPETH_WEB__PLUGIN_ALLOWLIST",
    "ELSPETH_WEB__PLUGIN_PREFERENCES",
    "ELSPETH_WEB__PLUGIN_CONTROL_MODES",
    "ELSPETH_WEB__LLM_PROFILES",
    "ELSPETH_WEB__DEFAULT_LLM_PROFILE",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_PROFILES",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_DEFAULT_PROFILES",
)
_TASK_DEFINITION_FAMILY_PATTERN = re.compile(
    r"arn:(?:aws|aws-us-gov|aws-cn):ecs:[a-z0-9-]+:[0-9]{12}:task-definition/([A-Za-z0-9_-]{1,255}):[1-9][0-9]*\Z"
)


# Closed error-code vocabulary for the operator-facing failure envelope.
# Every non-check acceptance failure projects onto exactly one of these
# static codes; unknown exceptions map to ``acceptance_internal``.  Codes
# never carry provider or server response content.
ACCEPTANCE_ERROR_CODES = frozenset(
    {
        "state_file_unwritable",
        "state_file_unreadable",
        "state_file_untrusted",
        "state_file_too_large",
        "state_file_invalid",
        "ca_unreadable",
        "connection_failed",
        "request_timeout",
        "unexpected_http_status",
        "response_too_large",
        "response_shape_invalid",
        "cross_origin_response",
        "input_invalid",
        "operator_telemetry_failed",
        "acceptance_internal",
    }
)

# Closed step vocabulary: the coarse acceptance phase that was executing
# when a failure surfaced.  Step names are static and never derived from
# runtime data.
ACCEPTANCE_STEPS = frozenset(
    {
        "env_validate",
        "client_setup",
        "register",
        "login",
        "capture_fetch",
        "verify_fetch",
        "state_persist",
        "state_load",
    }
)

_ACCEPTANCE_STEP: ContextVar[str | None] = ContextVar("elspeth_acceptance_step", default=None)


@contextlib.contextmanager
def acceptance_step(name: str) -> Iterator[None]:
    """Tag the executing acceptance step for the failure envelope.

    On success the previous step is restored; on failure the innermost
    step deliberately stays set so the top-level envelope can report it.
    """

    if name not in ACCEPTANCE_STEPS:
        raise ValueError(f"unknown acceptance step: {name}")
    token = _ACCEPTANCE_STEP.set(name)
    yield
    _ACCEPTANCE_STEP.reset(token)


def current_acceptance_step() -> str | None:
    """Return the innermost recorded acceptance step, if any."""

    return _ACCEPTANCE_STEP.get()


def reset_acceptance_step() -> None:
    """Clear any step left set by a previously failed invocation."""

    _ACCEPTANCE_STEP.set(None)


def _closed_error_code(error_code: str) -> str:
    return error_code if error_code in ACCEPTANCE_ERROR_CODES else "acceptance_internal"


class AcceptanceInputError(RuntimeError):
    """Static failure raised before an acceptance request is sent."""

    error_code = "input_invalid"
    status: int | None = None


class AcceptanceHttpError(RuntimeError):
    """Static HTTP failure that never includes a response or exception body."""

    def __init__(self, message: str, *, error_code: str = "connection_failed", status: int | None = None) -> None:
        super().__init__(message)
        self.error_code = _closed_error_code(error_code)
        self.status = status


class AcceptanceStateError(RuntimeError):
    """Static protected-state failure that never includes file content."""

    def __init__(self, message: str, *, error_code: str = "state_file_invalid") -> None:
        super().__init__(message)
        self.error_code = _closed_error_code(error_code)
        self.status: int | None = None


class AcceptanceCheckError(RuntimeError):
    """A static named acceptance check failure safe for operator output."""

    def __init__(
        self,
        check: str,
        *,
        missing: tuple[str, ...] | None = None,
        cause_class: str | None = None,
        cause_fields: tuple[str, ...] | None = None,
    ) -> None:
        super().__init__(f"acceptance check failed: {check}")
        self.check = check
        self.missing = missing
        self.cause_class = cause_class
        self.cause_fields = cause_fields


_CAUSE_FIELD_TOKEN = re.compile(r"\bELSPETH_[A-Z0-9_]*[A-Z0-9]\b")
_REDACTED_LOC_SEGMENT = "<redacted>"


def _nested_models(annotation: object) -> Iterator[type[BaseModel]]:
    """Yield every ``BaseModel`` subclass reachable in a field's type args.

    Walks ``Mapping[str, X]``, ``X | None``, ``tuple[X, ...]``, etc. down to
    their type arguments so a nested settings model (e.g. ``LLMProfileSettings``
    inside ``Mapping[str, LLMProfileSettings]``) is found regardless of the
    generic container it sits behind.
    """
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        yield annotation
        return
    for arg in typing.get_args(annotation):
        yield from _nested_models(arg)


def _static_schema_field_names(model: type[BaseModel], *, _seen: frozenset[type[BaseModel]] = frozenset()) -> frozenset[str]:
    """Recursively collect every field name declared by ``model`` and its nested models.

    A ``Mapping[str, X]``-typed field (e.g. ``WebSettings.llm_profiles``) puts
    the operator-chosen dict KEY in the same ``loc`` tuple position as a
    static field name — pydantic's ``errors()`` does not distinguish the two.
    This set is the whitelist of identifiers ELSPETH's own schema declares;
    anything at a ``loc`` position that is not in it is parsed data (a
    mapping key), never a name ELSPETH owns, and must be redacted before
    reaching operator-visible evidence.
    """
    if model in _seen:
        return frozenset()
    seen = _seen | {model}
    names: set[str] = set()
    for field_name, field_info in model.model_fields.items():
        names.add(field_name)
        for nested in _nested_models(field_info.annotation):
            names |= _static_schema_field_names(nested, _seen=seen)
    return frozenset(names)


_STATIC_SCHEMA_FIELD_NAMES: typing.Final[frozenset[str]] = _static_schema_field_names(WebSettings)


def _safe_loc_segment(part: object) -> str:
    """Render one pydantic ``loc`` element, redacting anything not a declared field name.

    Integer indices (list/tuple positions) are structural, not data, and pass
    through unredacted. String segments are checked against the static
    schema whitelist so an operator-controlled mapping key (a profile alias,
    for example) can never reach the envelope verbatim.
    """
    if isinstance(part, int):
        return str(part)
    text = str(part)
    return text if text in _STATIC_SCHEMA_FIELD_NAMES else _REDACTED_LOC_SEGMENT


def check_error_with_cause(check: str, exc: BaseException) -> AcceptanceCheckError:
    """Build a named check failure carrying only static cause identity.

    A bare ``AcceptanceCheckError("storage_settings")`` proved undiagnosable
    in the field (elspeth-dfd09564d5): the operator could not tell a missing
    setting from a type error from an unknown key without extracting the
    module from the image. This projection keeps the envelope fail-closed —
    it emits the underlying exception CLASS name plus static identifiers
    only: pydantic field locations when the exception exposes ``errors()``,
    otherwise ``ELSPETH_*`` environment-variable tokens found in the message.
    Message text and values are never emitted. Field-location segments that
    are not themselves a declared schema field name (a mapping key, e.g. an
    ``llm_profiles`` alias) are redacted rather than emitted verbatim.
    """
    fields: tuple[str, ...] = ()
    errors = getattr(exc, "errors", None)
    if callable(errors):
        with contextlib.suppress(Exception):
            fields = tuple(
                dict.fromkeys(
                    location
                    for error in errors()
                    if isinstance(error, Mapping)
                    for location in (".".join(_safe_loc_segment(part) for part in error.get("loc", ())),)
                    if location
                )
            )
    if not fields:
        fields = tuple(dict.fromkeys(_CAUSE_FIELD_TOKEN.findall(str(exc))))
    return AcceptanceCheckError(
        check,
        cause_class=type(exc).__name__,
        cause_fields=fields or None,
    )


class OperatorTelemetryAcceptanceError(RuntimeError):
    """Static acceptance failure safe for an operator receipt."""

    error_code = "operator_telemetry_failed"
    status: int | None = None


def acceptance_error_envelope(exc: BaseException) -> dict[str, object]:
    """Project one acceptance failure onto the closed operator envelope.

    The projection is fail-closed: it only ever emits the static exception
    class name, a code from :data:`ACCEPTANCE_ERROR_CODES` (or the static
    check name), the closed step vocabulary, an integer HTTP status, and —
    for missing live inputs — static environment variable names.  Response
    bodies, paths, tokens, and exception text are never included.
    """

    envelope: dict[str, object] = {
        "error_class": type(exc).__name__,
        "step": current_acceptance_step(),
    }
    if isinstance(exc, AcceptanceCheckError):
        envelope["check"] = exc.check
        if exc.missing:
            envelope["missing"] = sorted(exc.missing)
        if exc.cause_class is not None:
            envelope["cause_class"] = exc.cause_class
        if exc.cause_fields:
            envelope["cause_fields"] = sorted(exc.cause_fields)
        return envelope
    error_code = getattr(exc, "error_code", None)
    envelope["error_code"] = error_code if isinstance(error_code, str) and error_code in ACCEPTANCE_ERROR_CODES else "acceptance_internal"
    status = getattr(exc, "status", None)
    if type(status) is int:
        envelope["status"] = status
    return envelope


def normalize_acceptance_origin(raw: str) -> str:
    """Validate and return one exact canonical acceptance origin."""

    try:
        parsed = urlsplit(raw)
        hostname = parsed.hostname
        port = parsed.port
    except ValueError:
        raise AcceptanceInputError("acceptance base origin is invalid") from None
    if (
        not raw
        or parsed.scheme not in {"http", "https"}
        or hostname is None
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path
        or parsed.query
        or parsed.fragment
    ):
        raise AcceptanceInputError("acceptance base origin is invalid")
    try:
        hostname.encode("ascii")
    except UnicodeEncodeError:
        raise AcceptanceInputError("acceptance base origin is invalid") from None
    if parsed.scheme == "http" and hostname not in _LOOPBACK_HOSTS:
        raise AcceptanceInputError("acceptance base origin requires HTTPS except for exact loopback hosts")
    if port is not None and not 1 <= port <= 65535:
        raise AcceptanceInputError("acceptance base origin is invalid")

    default_port = 443 if parsed.scheme == "https" else 80
    rendered_host = f"[{hostname}]" if ":" in hostname else hostname
    canonical = f"{parsed.scheme}://{rendered_host}"
    if port is not None and port != default_port:
        canonical = f"{canonical}:{port}"
    if raw != canonical:
        raise AcceptanceInputError("acceptance base origin must be an exact normalized origin")
    return canonical


def _canonical_uuid(value: str, *, label: str) -> str:
    try:
        parsed = uuid.UUID(value)
    except (ValueError, AttributeError):
        raise AcceptanceInputError(f"acceptance {label} is invalid") from None
    if str(parsed) != value:
        raise AcceptanceInputError(f"acceptance {label} is invalid")
    return value


def _mapping(value: object, *, check: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise AcceptanceCheckError(check)
    return value


def _string_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    candidate = value.get(field)
    if type(candidate) is not str or not candidate:
        raise AcceptanceCheckError(check)
    return candidate


def _uuid_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    candidate = _string_field(value, field, check=check)
    try:
        return _canonical_uuid(candidate, label="response identity")
    except AcceptanceInputError:
        raise AcceptanceCheckError(check) from None


def _sha256_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    candidate = _string_field(value, field, check=check)
    if _SHA256_PATTERN.fullmatch(candidate) is None:
        raise AcceptanceCheckError(check)
    return candidate


def _artifact_id_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    """Validate a landscape ``artifacts.artifact_id`` value.

    See ``_ARTIFACT_ID_PATTERN`` for why this is not ``_uuid_field``: the
    real value is a lowercase hex string (32 or 64 chars depending on
    producer path), never a canonical dashed UUID.
    """
    candidate = _string_field(value, field, check=check)
    if _ARTIFACT_ID_PATTERN.fullmatch(candidate) is None:
        raise AcceptanceCheckError(check)
    return candidate


def _sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def scenario_resource_namespace(acceptance_run_id: str, scenario_id: str) -> str:
    """Return the stable AWS-name-safe namespace for one acceptance scenario."""

    try:
        canonical_run_id = _canonical_uuid(acceptance_run_id, label="acceptance run ID")
    except AcceptanceInputError:
        raise AcceptanceCheckError("scenario_inventory_binding") from None
    if scenario_id not in {"A", "B", "C"}:
        raise AcceptanceCheckError("scenario_inventory_binding")
    digest = _sha256(f"{canonical_run_id}\0{scenario_id}".encode())[:20]
    return f"{scenario_id.lower()}-{digest}"


def plugin_policy_binding_sha256(values: Mapping[str, str]) -> str:
    """Hash the exact protected seven-setting web policy assignment."""

    projection: dict[str, str] = {}
    for name in PLUGIN_POLICY_ASSIGNMENT_NAMES:
        value = values.get(name)
        if type(value) is not str or not value or len(value) > 16 * 1024:
            raise AcceptanceCheckError("plugin_policy_binding")
        if any(ord(character) < 32 or ord(character) == 127 for character in value):
            raise AcceptanceCheckError("plugin_policy_binding")
        projection[name] = value
    encoded = json.dumps(projection, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256(encoded)


def _utc_timestamp(value: datetime) -> str:
    if value.tzinfo is None or value.utcoffset() is None:
        raise AcceptanceCheckError("timestamp")
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _parse_utc_z_timestamp(value: str) -> datetime:
    """Parse one strict UTC timestamp ending in ``Z``."""

    if type(value) is not str or not value.endswith("Z"):
        raise ValueError("timestamp must be a UTC Z timestamp")
    try:
        parsed = datetime.fromisoformat(f"{value[:-1]}+00:00")
    except ValueError:
        raise ValueError("timestamp must be a UTC Z timestamp") from None
    if parsed.tzinfo != UTC:
        raise ValueError("timestamp must be a UTC Z timestamp")
    return parsed


def _control_timestamp(value: object) -> datetime:
    if type(value) is not str:
        raise AcceptanceCheckError("control_manifest_schema")
    try:
        return _parse_utc_z_timestamp(value)
    except ValueError:
        raise AcceptanceCheckError("control_manifest_schema") from None


def _bounded_identity(field: str, value: str) -> str:
    if (
        not value.strip()
        or value != value.strip()
        or len(value) > _MAX_IDENTITY_CHARS
        or any(ord(char) < 32 or ord(char) == 127 for char in value)
    ):
        raise ValueError(f"{field} must be a non-blank bounded string without control characters")
    return value


@dataclass(frozen=True, slots=True)
class SanitizedResourceIdentity:
    """Closed non-content identity persisted in acceptance evidence."""

    service_name: str
    service_version: str
    deployment_environment: str
    cloud_provider: str

    def __post_init__(self) -> None:
        _bounded_identity("service_name", self.service_name)
        _bounded_identity("service_version", self.service_version)
        _bounded_identity("deployment_environment", self.deployment_environment)
        _bounded_identity("cloud_provider", self.cloud_provider)
        if self.cloud_provider != "aws":
            raise ValueError("cloud_provider must be aws")


def _resolve_aws_region(env: Mapping[str, str], *, check: str) -> str:
    primary_region = env.get("AWS_REGION")
    default_region = env.get("AWS_DEFAULT_REGION")
    if primary_region is not None and not primary_region:
        raise AcceptanceCheckError(check)
    if default_region is not None and not default_region:
        raise AcceptanceCheckError(check)
    if primary_region is not None and default_region is not None and primary_region != default_region:
        raise AcceptanceCheckError(check)
    region = primary_region or default_region
    if region is None or len(region) > 64 or re.fullmatch(r"[A-Za-z0-9-]+", region) is None:
        raise AcceptanceCheckError(check)
    return region


def _resolve_acceptance_s3_location(env: Mapping[str, str], *, check: str) -> tuple[str, str, str]:
    """Validate and return the acceptance (bucket, prefix, region) triple."""

    bucket = env.get("ELSPETH_ACCEPTANCE_S3_BUCKET")
    prefix = env.get("ELSPETH_ACCEPTANCE_S3_PREFIX")
    if type(bucket) is not str or not bucket.strip() or len(bucket) > 2048:
        raise AcceptanceCheckError(check)
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in bucket):
        raise AcceptanceCheckError(check)
    if type(prefix) is not str or not prefix or prefix != prefix.strip("/"):
        raise AcceptanceCheckError(check)
    segments = prefix.split("/")
    if any(not segment or segment in {".", ".."} for segment in segments):
        raise AcceptanceCheckError(check)
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in prefix):
        raise AcceptanceCheckError(check)
    try:
        _canonical_uuid(segments[-1], label="S3 prefix identity")
    except AcceptanceInputError:
        raise AcceptanceCheckError(check) from None
    region = _resolve_aws_region(env, check=check)
    return bucket, prefix, region


def _parse_task_definition_family(task_definition_arn: object) -> str | None:
    """Return the ECS task-definition family, or no match for invalid input."""

    if type(task_definition_arn) is not str:
        return None
    match = _TASK_DEFINITION_FAMILY_PATTERN.fullmatch(task_definition_arn)
    return None if match is None else match.group(1)


def _task_definition_family(task_definition_arn: object) -> str:
    family = _parse_task_definition_family(task_definition_arn)
    if family is None:
        raise AcceptanceCheckError("orphan_sweep_api")
    return family
