"""Shared contracts and pure helpers for AWS ECS acceptance.

The provider-neutral core (error vocabulary and step contextvar, bounded
identities, digest and timestamp helpers, the HTTP client's bounds and origin
normaliser) lives in ``elspeth.web._acceptance_common`` and is re-imported here
by identity, so every ECS module, the facade and the ECS tests keep reaching
those names through this module unchanged.
"""

from __future__ import annotations

import json
import re
import sys
import typing
import uuid
from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from datetime import datetime

from pydantic import BaseModel

from elspeth.contracts.trust_boundary import trust_boundary
from elspeth.web._acceptance_common.errors import ACCEPTANCE_ERROR_CODES as ACCEPTANCE_ERROR_CODES
from elspeth.web._acceptance_common.errors import ACCEPTANCE_STEPS as ACCEPTANCE_STEPS
from elspeth.web._acceptance_common.errors import AcceptanceCheckError as AcceptanceCheckError
from elspeth.web._acceptance_common.errors import AcceptanceHttpError as AcceptanceHttpError
from elspeth.web._acceptance_common.errors import AcceptanceInputError as AcceptanceInputError
from elspeth.web._acceptance_common.errors import AcceptanceStateError as AcceptanceStateError
from elspeth.web._acceptance_common.errors import _closed_error_code as _closed_error_code
from elspeth.web._acceptance_common.errors import acceptance_step as acceptance_step
from elspeth.web._acceptance_common.errors import current_acceptance_step as current_acceptance_step
from elspeth.web._acceptance_common.errors import reset_acceptance_step as reset_acceptance_step
from elspeth.web._acceptance_common.http_client import _LOOPBACK_HOSTS as _LOOPBACK_HOSTS
from elspeth.web._acceptance_common.http_client import CONNECT_TIMEOUT_SECONDS as CONNECT_TIMEOUT_SECONDS
from elspeth.web._acceptance_common.http_client import MAX_BLOB_RESPONSE_BYTES as MAX_BLOB_RESPONSE_BYTES
from elspeth.web._acceptance_common.http_client import MAX_JSON_RESPONSE_BYTES as MAX_JSON_RESPONSE_BYTES
from elspeth.web._acceptance_common.http_client import POOL_TIMEOUT_SECONDS as POOL_TIMEOUT_SECONDS
from elspeth.web._acceptance_common.http_client import READ_TIMEOUT_SECONDS as READ_TIMEOUT_SECONDS
from elspeth.web._acceptance_common.http_client import WRITE_TIMEOUT_SECONDS as WRITE_TIMEOUT_SECONDS
from elspeth.web._acceptance_common.http_client import normalize_acceptance_origin as normalize_acceptance_origin
from elspeth.web._acceptance_common.identity import _MAX_IDENTITY_CHARS as _MAX_IDENTITY_CHARS
from elspeth.web._acceptance_common.identity import SanitizedResourceIdentity as SanitizedResourceIdentity
from elspeth.web._acceptance_common.identity import _bounded_identity as _bounded_identity
from elspeth.web._acceptance_common.receipt_validation import _GIT_SHA_PATTERN as _GIT_SHA_PATTERN
from elspeth.web._acceptance_common.receipt_validation import _SCENARIO_ID_PATTERN as _SCENARIO_ID_PATTERN
from elspeth.web._acceptance_common.receipt_validation import _SHA256_PATTERN as _SHA256_PATTERN
from elspeth.web._acceptance_common.receipt_validation import MAX_EXEC_RECEIPT_CHARS as MAX_EXEC_RECEIPT_CHARS
from elspeth.web._acceptance_common.receipt_validation import MAX_EXEC_STREAM_BYTES as MAX_EXEC_STREAM_BYTES
from elspeth.web._acceptance_common.receipt_validation import _parse_utc_z_timestamp as _parse_utc_z_timestamp
from elspeth.web._acceptance_common.receipt_validation import _sha256 as _sha256
from elspeth.web._acceptance_common.receipt_validation import _utc_timestamp as _utc_timestamp
from elspeth.web._acceptance_common.secure_documents import MAX_CONTROL_DOCUMENT_BYTES as MAX_CONTROL_DOCUMENT_BYTES
from elspeth.web.config import WebSettings

_EVIDENCE_KINDS = (
    "web-log",
    "doctor-log",
    "deployment-event",
    "task-definition",
    "terraform-plan",
    "terraform-destroy-plan",
)
EVIDENCE_KINDS = _EVIDENCE_KINDS
RUN_POLL_DEADLINE_SECONDS = 5 * 60
RUN_POLL_INTERVAL_SECONDS = 1.0
MAX_STATE_FILE_BYTES = 64 * 1024
_EMERGENCY_CLEANUP_SECONDS = 3 * 60 * 60
# `artifacts.artifact_id` (elspeth.core.landscape.schema) is a
# ``String(64)`` column, NOT a UUID column, and is never generated by
# ``uuid.uuid4()``: the sink-effect producer path (the only live producer,
# ``elspeth.core.landscape.execution.sink_effect_finalization``) derives it
# via a labeled SHA-256 digest (64 lowercase hex chars); the legacy
# ``core.ids.generate_id()`` default is a bare ``uuid4().hex`` (32 lowercase
# hex chars, no dashes). Neither shape is a canonical dashed UUID, unlike
# session/blob/run/landscape-run identities (all genuine
# ``str(uuid.uuid4())`` DB values elsewhere in the web layer). Only the two
# live producer widths are valid.
_ARTIFACT_ID_PATTERN = re.compile(r"(?:[0-9a-f]{32}|[0-9a-f]{64})\Z")
_TERMINAL_RUN_STATUSES = frozenset({"completed", "completed_with_failures", "failed", "empty", "cancelled"})
FORBIDDEN_AWS_OVERRIDE_ENV = frozenset(
    {
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_SESSION_TOKEN",
        "AWS_SECURITY_TOKEN",
        "AWS_CREDENTIAL_EXPIRATION",
        "AWS_PROFILE",
        "AWS_DEFAULT_PROFILE",
        "AWS_CONFIG_FILE",
        "AWS_SHARED_CREDENTIALS_FILE",
        "AWS_CREDENTIAL_FILE",
        "BOTO_CONFIG",
        "AWS_ENDPOINT_URL",
        "AWS_ENDPOINT_URL_S3",
        "AWS_ENDPOINT_URL_BEDROCK",
        "AWS_ENDPOINT_URL_BEDROCK_RUNTIME",
        "AWS_ENDPOINT_URL_CLOUDWATCH",
        "AWS_ENDPOINT_URL_XRAY",
        "AWS_EC2_METADATA_SERVICE_ENDPOINT",
        "AWS_ROLE_ARN",
        "AWS_WEB_IDENTITY_TOKEN_FILE",
        "AWS_ROLE_SESSION_NAME",
        "AWS_CONTAINER_CREDENTIALS_FULL_URI",
        "AWS_CONTAINER_AUTHORIZATION_TOKEN",
        "AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE",
    }
)
SCENARIO_ASSIGNMENT_NAMES = (
    "ACTIVE_SCENARIO_ID",
    "ACCEPTANCE_RUN_ID",
    "DEPLOYMENT_MODE",
    "TARGET_PLATFORM",
    "AWS_REGION",
    "ECS_CLUSTER",
    "ECS_SERVICE",
    "WEB_CONTAINER_NAME",
    "ELSPETH_WEB__DATA_DIR",
    "ELSPETH_WEB__PAYLOAD_STORE_PATH",
    "ELSPETH_WEB__COMPOSER_MODEL",
    "ELSPETH_WEB__COMPOSER_ADVISOR_MODEL",
    "ELSPETH_WEB__PLUGIN_ALLOWLIST",
    "ELSPETH_WEB__PLUGIN_PREFERENCES",
    "ELSPETH_WEB__PLUGIN_CONTROL_MODES",
    "ELSPETH_WEB__LLM_PROFILES",
    "ELSPETH_WEB__DEFAULT_LLM_PROFILE",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_PROFILES",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_DEFAULT_PROFILES",
    "ELSPETH_ACCEPTANCE_PLUGIN_POLICY_BINDING_SHA256",
    "ELSPETH_BEDROCK_LIVE_TEST_MODEL",
    "CLOUDWATCH_AGENT_IMAGE",
    "CLOUDWATCH_AGENT_CONFIG_JSON_SHA256",
    "CLOUDWATCH_AGENT_OTEL_YAML_SHA256",
    "TARGET_GROUP_ARN",
    "ALB_BASE_URL",
    "ALB_ARN",
    "CANDIDATE_TASK_DEFINITION",
    "DOCTOR_TASK_DEFINITION",
    "DOCTOR_CONTAINER_NAME",
    "DOCTOR_NETWORK_CONFIGURATION",
    "PAYLOAD_VERIFIER_TASK_DEFINITION",
    "LOCAL_AUTH_VERIFIER_TASK_DEFINITION",
    "ROLLBACK_DOCTOR_TASK_DEFINITION",
    "WEB_LOG_GROUP",
    "WEB_LOG_STREAM_PREFIX",
    "DOCTOR_LOG_GROUP",
    "DOCTOR_LOG_STREAM_PREFIX",
    "OPERATOR_METRICS_LOG_GROUP",
    "ECS_DEPLOYMENT_EVENT_RULE",
    "ECS_DEPLOYMENT_EVENT_TARGET_ID",
    "ECS_DEPLOYMENT_EVENT_LOG_GROUP",
    "PREVIOUS_TASK_DEFINITION",
    "FIRST_DEPLOY_LISTENER_RULE_ARN",
    "FIRST_DEPLOY_FORWARD_ACTIONS",
    "FIRST_DEPLOY_DISABLED_ACTIONS",
    "COGNITO_USER_POOL_ID",
    "DB_CLUSTER_IDENTIFIER",
    "ELSPETH_TEST_S3_BUCKET",
    "OIDC_EXPECTED_ISSUER",
    "OIDC_EXPECTED_AUDIENCE",
    "OIDC_EXPECTED_AUTHORIZATION_ORIGIN",
    "OIDC_EXPECTED_AUDIENCE_CLAIM",
    "SCENARIO_TF_DIR",
    "SCENARIO_TF_VARS",
    "SCENARIO_TF_BINDING_SHA",
    "SCENARIO_TF_BINDING_FILE",
)
SCENARIO_VALUE_FIELDS = frozenset(SCENARIO_ASSIGNMENT_NAMES[2:])
_SCENARIO_VALUE_FIELDS = SCENARIO_VALUE_FIELDS
PLUGIN_POLICY_ASSIGNMENT_NAMES = (
    "ELSPETH_WEB__PLUGIN_ALLOWLIST",
    "ELSPETH_WEB__PLUGIN_PREFERENCES",
    "ELSPETH_WEB__PLUGIN_CONTROL_MODES",
    "ELSPETH_WEB__LLM_PROFILES",
    "ELSPETH_WEB__DEFAULT_LLM_PROFILE",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_PROFILES",
    "ELSPETH_WEB__BEDROCK_GUARDRAIL_DEFAULT_PROFILES",
)
_TASK_DEFINITION_FAMILY_PATTERN = re.compile(
    r"arn:(?:aws|aws-us-gov|aws-cn):ecs:[a-z0-9-]+:[0-9]{12}:task-definition/([A-Za-z0-9_-]{1,255}):[1-9][0-9]*\Z"
)


_CAUSE_FIELD_TOKEN = re.compile(r"\bELSPETH_[A-Z0-9_]*[A-Z0-9]\b")
_REDACTED_LOC_SEGMENT = "<redacted>"
_CAUSE_INTROSPECTION_FAILED = "<cause-introspection-failed>"


def _nested_models(annotation: object) -> Iterator[type[BaseModel]]:
    """Yield every ``BaseModel`` subclass reachable in a field's type args.

    Walks ``Mapping[str, X]``, ``X | None``, ``tuple[X, ...]``, etc. down to
    their type arguments so a nested settings model (e.g. ``LLMProfileSettings``
    inside ``Mapping[str, LLMProfileSettings]``) is found regardless of the
    generic container it sits behind.
    """
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        yield annotation
        return
    for arg in typing.get_args(annotation):
        yield from _nested_models(arg)


def _static_schema_field_names(model: type[BaseModel], *, _seen: frozenset[type[BaseModel]] = frozenset()) -> frozenset[str]:
    """Recursively collect every field name declared by ``model`` and its nested models.

    A ``Mapping[str, X]``-typed field (e.g. ``WebSettings.llm_profiles``) puts
    the operator-chosen dict KEY in the same ``loc`` tuple position as a
    static field name — pydantic's ``errors()`` does not distinguish the two.
    This set is the whitelist of identifiers ELSPETH's own schema declares;
    anything at a ``loc`` position that is not in it is parsed data (a
    mapping key), never a name ELSPETH owns, and must be redacted before
    reaching operator-visible evidence.
    """
    if model in _seen:
        return frozenset()
    seen = _seen | {model}
    names: set[str] = set()
    for field_name, field_info in model.model_fields.items():
        names.add(field_name)
        for nested in _nested_models(field_info.annotation):
            names |= _static_schema_field_names(nested, _seen=seen)
    return frozenset(names)


_STATIC_SCHEMA_FIELD_NAMES: typing.Final[frozenset[str]] = _static_schema_field_names(WebSettings)


def _safe_loc_segment(part: object) -> str:
    """Render one pydantic ``loc`` element, redacting anything not a declared field name.

    Integer indices (list/tuple positions) are structural, not data, and pass
    through unredacted. String segments are checked against the static
    schema whitelist so an operator-controlled mapping key (a profile alias,
    for example) can never reach the envelope verbatim.
    """
    if type(part) is int:
        return str(part)
    text = str(part)
    return text if text in _STATIC_SCHEMA_FIELD_NAMES else _REDACTED_LOC_SEGMENT


@trust_boundary(
    tier=3,
    source="an exception object raised by a settings or storage loader ELSPETH does not own (a pydantic ValidationError, or any third-party exception)",
    source_param="exc",
    suppresses=("R1", "R5"),
    invariant=(
        "never raises on exc: evaluates str(exc) and probes errors() behind a sentinel getattr inside one "
        "typed try/except whose failure path returns the static <cause-introspection-failed> token, admits "
        "only Mapping error entries, "
        "redacts every loc segment that is not a declared WebSettings field name, and falls back to static "
        "ELSPETH_* message tokens; returns a static AcceptanceCheckError carrying only the exception class "
        "name and redacted field identifiers, never message text or parsed values"
    ),
    non_raising=True,
)
def check_error_with_cause(check: str, exc: BaseException) -> AcceptanceCheckError:
    """Build a named check failure carrying only static cause identity.

    A bare ``AcceptanceCheckError("storage_settings")`` proved undiagnosable
    in the field (elspeth-dfd09564d5): the operator could not tell a missing
    setting from a type error from an unknown key without extracting the
    module from the image. This projection keeps the envelope fail-closed —
    it emits the underlying exception CLASS name plus static identifiers
    only: pydantic field locations when the exception exposes ``errors()``,
    otherwise ``ELSPETH_*`` environment-variable tokens found in the message.
    Message text and values are never emitted. Field-location segments that
    are not themselves a declared schema field name (a mapping key, e.g. an
    ``llm_profiles`` alias) are redacted rather than emitted verbatim.
    """
    # str(exc) and errors() are third-party code. If either raises, the
    # degradation is surfaced as the static ``<cause-introspection-failed>``
    # token in cause_fields (operator-visible in the failure envelope) rather
    # than silently dropping the enrichment. The token is static text, so the
    # redaction contract — no message text, no parsed values — holds on the
    # failure path too.
    try:
        fields = tuple(dict.fromkeys(_CAUSE_FIELD_TOKEN.findall(str(exc))))
        errors = getattr(exc, "errors", None)
        if callable(errors):
            fields = (
                tuple(
                    dict.fromkeys(
                        location
                        for error in errors()
                        if isinstance(error, Mapping)
                        for location in (".".join(_safe_loc_segment(part) for part in error.get("loc", ())),)
                        if location
                    )
                )
                or fields
            )
    except Exception:
        return AcceptanceCheckError(
            check,
            cause_class=type(exc).__name__,
            cause_fields=(_CAUSE_INTROSPECTION_FAILED,),
        )
    return AcceptanceCheckError(
        check,
        cause_class=type(exc).__name__,
        cause_fields=fields or None,
    )


@dataclass(frozen=True, slots=True)
class CheckFailureRecord:
    """One recorded acceptance-step failure: static check id plus cause class.

    The exception class name is the only cause identity retained — message
    text and values never enter operator-visible evidence (same redaction
    discipline as :class:`AcceptanceCheckError`).
    """

    check: str
    exception_type: str | None = None


def check_failure_error(check: str, failures: typing.Sequence[CheckFailureRecord]) -> AcceptanceCheckError:
    """Build the declared failure result for ``check`` from recorded failures."""

    record = next((entry for entry in failures if entry.check == check and entry.exception_type is not None), None)
    return AcceptanceCheckError(check, cause_class=record.exception_type if record is not None else None)


class _SupportsClose(typing.Protocol):
    """Typing-only shape for closeable probe resources (never used for dispatch)."""

    def close(self) -> object: ...


def close_failure(resource: _SupportsClose, *, check: str) -> CheckFailureRecord | None:
    """Close one probe resource; report failure as a record instead of raising.

    A close failure is never silently dropped: on the unwind path (an
    exception already in flight) it is additionally attached to the
    propagating exception as a PEP 678 note, and on the normal path the
    caller converts the returned record into the probe's declared
    ``AcceptanceCheckError``. Only the exception class name is retained.
    """

    active = sys.exc_info()[1]
    try:
        resource.close()
    except Exception as exc:
        record = CheckFailureRecord(check=check, exception_type=type(exc).__name__)
        if active is not None:
            active.add_note(f"acceptance resource close also failed during unwind: check={check} cause_class={record.exception_type}")
        return record
    return None


class OperatorTelemetryAcceptanceError(RuntimeError):
    """Static acceptance failure safe for an operator receipt."""

    error_code = "operator_telemetry_failed"
    status: int | None = None


def acceptance_error_envelope(exc: BaseException) -> dict[str, object]:
    """Project one acceptance failure onto the closed operator envelope.

    The projection is fail-closed: it only ever emits the static exception
    class name, a code from :data:`ACCEPTANCE_ERROR_CODES` (or the static
    check name), the closed step vocabulary, an integer HTTP status, and —
    for missing live inputs — static environment variable names.  Response
    bodies, paths, tokens, and exception text are never included.
    """

    envelope: dict[str, object] = {
        "error_class": type(exc).__name__,
        "step": current_acceptance_step(),
    }
    if isinstance(exc, AcceptanceCheckError):
        envelope["check"] = exc.check
        if exc.missing:
            envelope["missing"] = sorted(exc.missing)
        if exc.cause_class is not None:
            envelope["cause_class"] = exc.cause_class
        if exc.cause_fields:
            envelope["cause_fields"] = sorted(exc.cause_fields)
        return envelope
    if isinstance(exc, AcceptanceInputError | AcceptanceHttpError | AcceptanceStateError | OperatorTelemetryAcceptanceError):
        envelope["error_code"] = _closed_error_code(exc.error_code)
        if type(exc.status) is int:
            envelope["status"] = exc.status
    else:
        envelope["error_code"] = "acceptance_internal"
    return envelope


def _canonical_uuid(value: str, *, label: str) -> str:
    try:
        parsed = uuid.UUID(value)
    except (ValueError, AttributeError):
        raise AcceptanceInputError(f"acceptance {label} is invalid") from None
    if str(parsed) != value:
        raise AcceptanceInputError(f"acceptance {label} is invalid")
    return value


def _mapping(value: object, *, check: str) -> Mapping[str, object]:
    if type(value) is not dict:
        raise AcceptanceCheckError(check)
    return value


def _string_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    if field not in value:
        raise AcceptanceCheckError(check)
    candidate = value[field]
    if type(candidate) is not str or not candidate:
        raise AcceptanceCheckError(check)
    return candidate


def _uuid_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    candidate = _string_field(value, field, check=check)
    try:
        return _canonical_uuid(candidate, label="response identity")
    except AcceptanceInputError:
        raise AcceptanceCheckError(check) from None


def _sha256_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    candidate = _string_field(value, field, check=check)
    if _SHA256_PATTERN.fullmatch(candidate) is None:
        raise AcceptanceCheckError(check)
    return candidate


def _artifact_id_field(value: Mapping[str, object], field: str, *, check: str) -> str:
    """Validate a landscape ``artifacts.artifact_id`` value.

    See ``_ARTIFACT_ID_PATTERN`` for why this is not ``_uuid_field``: the
    real value is a lowercase hex string (32 or 64 chars depending on
    producer path), never a canonical dashed UUID.
    """
    candidate = _string_field(value, field, check=check)
    if _ARTIFACT_ID_PATTERN.fullmatch(candidate) is None:
        raise AcceptanceCheckError(check)
    return candidate


def scenario_resource_namespace(acceptance_run_id: str, scenario_id: str) -> str:
    """Return the stable AWS-name-safe namespace for one acceptance scenario."""

    try:
        canonical_run_id = _canonical_uuid(acceptance_run_id, label="acceptance run ID")
    except AcceptanceInputError:
        raise AcceptanceCheckError("scenario_inventory_binding") from None
    if scenario_id not in {"A", "B", "C"}:
        raise AcceptanceCheckError("scenario_inventory_binding")
    digest = _sha256(f"{canonical_run_id}\0{scenario_id}".encode())[:20]
    return f"{scenario_id.lower()}-{digest}"


def plugin_policy_binding_sha256(values: Mapping[str, str]) -> str:
    """Hash the exact protected seven-setting web policy assignment."""

    projection: dict[str, str] = {}
    for name in PLUGIN_POLICY_ASSIGNMENT_NAMES:
        if name not in values:
            raise AcceptanceCheckError("plugin_policy_binding")
        value = values[name]
        if type(value) is not str or not value or len(value) > 16 * 1024:
            raise AcceptanceCheckError("plugin_policy_binding")
        if any(ord(character) < 32 or ord(character) == 127 for character in value):
            raise AcceptanceCheckError("plugin_policy_binding")
        projection[name] = value
    encoded = json.dumps(projection, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256(encoded)


def _control_timestamp(value: object) -> datetime:
    if type(value) is not str:
        raise AcceptanceCheckError("control_manifest_schema")
    try:
        return _parse_utc_z_timestamp(value)
    except ValueError:
        raise AcceptanceCheckError("control_manifest_schema") from None


@trust_boundary(
    tier=3,
    source="the AWS region assignment (AWS_REGION / AWS_DEFAULT_REGION) in the acceptance harness process environment, set by the deployment rather than by ELSPETH",
    source_param="env",
    suppresses=("R1", "R5"),
    invariant=(
        "raises AcceptanceCheckError before use when both names are absent, when either is present but "
        "empty, when the two disagree, or when the resolved value exceeds 64 characters or is not "
        "[A-Za-z0-9-]+; returns only a validated region string and never coerces external values"
    ),
    test_ref=(
        "tests/unit/web/aws_ecs_acceptance/test_contracts_secure_state.py::"
        "test_resolve_aws_region_rejects_absent_blank_conflicting_or_malformed_assignments"
    ),
    test_fingerprint="d8d7c127beead7f8336731c80c8b0784843c3f116329277f8f9fe5e3f3ec10d1",
)
def _resolve_aws_region(env: Mapping[str, str], *, check: str) -> str:
    primary_region = env.get("AWS_REGION")
    default_region = env.get("AWS_DEFAULT_REGION")
    if primary_region is not None and not primary_region:
        raise AcceptanceCheckError(check)
    if default_region is not None and not default_region:
        raise AcceptanceCheckError(check)
    if primary_region is not None and default_region is not None and primary_region != default_region:
        raise AcceptanceCheckError(check)
    region = primary_region or default_region
    if region is None or len(region) > 64 or re.fullmatch(r"[A-Za-z0-9-]+", region) is None:
        raise AcceptanceCheckError(check)
    return region


@trust_boundary(
    tier=3,
    source="the acceptance S3 evidence-location assignment (ELSPETH_ACCEPTANCE_S3_BUCKET / ELSPETH_ACCEPTANCE_S3_PREFIX) in the acceptance harness process environment",
    source_param="env",
    suppresses=("R1", "R5"),
    invariant=(
        "raises AcceptanceCheckError before use on a bucket that is absent, blank, longer than 2048 "
        "characters or carries control characters, on a prefix that is absent, is not stripped of slashes, "
        "has an empty or dot segment, carries control characters, or whose final segment is not a canonical "
        "UUID, and on a region the AWS region assignment cannot resolve; returns only a validated "
        "(bucket, prefix, region) triple and never coerces external values"
    ),
    test_ref=(
        "tests/unit/web/aws_ecs_acceptance/test_contracts_secure_state.py::"
        "test_resolve_acceptance_s3_location_rejects_malformed_bucket_prefix_or_region"
    ),
    test_fingerprint="73e3fe8d4a1d24652a00802cb924244f1e279fb87e8f798ec3ddeb690031a9e7",
)
def _resolve_acceptance_s3_location(env: Mapping[str, str], *, check: str) -> tuple[str, str, str]:
    """Validate and return the acceptance (bucket, prefix, region) triple."""

    bucket = env.get("ELSPETH_ACCEPTANCE_S3_BUCKET")
    prefix = env.get("ELSPETH_ACCEPTANCE_S3_PREFIX")
    if type(bucket) is not str or not bucket.strip() or len(bucket) > 2048:
        raise AcceptanceCheckError(check)
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in bucket):
        raise AcceptanceCheckError(check)
    if type(prefix) is not str or not prefix or prefix != prefix.strip("/"):
        raise AcceptanceCheckError(check)
    segments = prefix.split("/")
    if any(not segment or segment in {".", ".."} for segment in segments):
        raise AcceptanceCheckError(check)
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in prefix):
        raise AcceptanceCheckError(check)
    try:
        _canonical_uuid(segments[-1], label="S3 prefix identity")
    except AcceptanceInputError:
        raise AcceptanceCheckError(check) from None
    region = _resolve_aws_region(env, check=check)
    return bucket, prefix, region


def _parse_task_definition_family(task_definition_arn: object) -> str | None:
    """Return the ECS task-definition family, or no match for invalid input."""

    if type(task_definition_arn) is not str:
        return None
    match = _TASK_DEFINITION_FAMILY_PATTERN.fullmatch(task_definition_arn)
    return None if match is None else match.group(1)


def _task_definition_family(task_definition_arn: object) -> str:
    family = _parse_task_definition_family(task_definition_arn)
    if family is None:
        raise AcceptanceCheckError("orphan_sweep_api")
    return family
