// src/test/redactedArgumentFixture.ts
//
// Reads the committed fixture of REAL redacted tool-call arguments so
// frontend tests can be driven by what the producer actually emits.
//
// Why this exists (elspeth-b1c14dd3c2): the proposal surface renders
// `arguments_redacted_json`, and four projection arms shipped dead because
// their tests hand-built that payload as a plain object — a shape the
// redactor never produces. A test that constructs its own input in a shape
// the producer cannot emit certifies nothing about the producer, so the input
// has to come FROM the producer.
//
// The fixture is generated by
// `scripts/cicd/bootstrap_proposal_diff_fixture.py --write`, which calls
// `redact_tool_call_arguments` directly, and is pinned against the live
// redactor by `tests/unit/web/composer/test_proposal_diff_redaction_fixture.py`.
// If the redaction grammar changes, that Python test fails — the frontend
// cannot silently drift behind the backend the way it did before.

import { readFileSync } from "node:fs";

// Relative to the vitest working directory, which is this frontend package
// (the same convention src/test/playwrightConfig.test.ts uses).
const FIXTURE_PATH = "src/test/fixtures/redacted-tool-arguments.json";

export interface RedactedArgumentCase {
  /** The composer tool the arguments were redacted for. */
  tool: string;
  /** The pre-redaction arguments, recorded so the Python pin can re-derive. */
  arguments: Record<string, unknown>;
  /** What `redact_tool_call_arguments` returned — what the UI really gets. */
  redacted: Record<string, unknown>;
}

interface RedactedArgumentFixture {
  _regenerate: string;
  cases: Record<string, RedactedArgumentCase>;
}

let cachedFixture: RedactedArgumentFixture | null = null;

function loadFixture(): RedactedArgumentFixture {
  if (cachedFixture === null) {
    cachedFixture = JSON.parse(
      readFileSync(FIXTURE_PATH, "utf8"),
    ) as RedactedArgumentFixture;
  }
  return cachedFixture;
}

/** The whole recorded case, for tests that also assert on the tool name. */
export function redactedCase(caseName: string): RedactedArgumentCase {
  const fixture = loadFixture();
  const recorded = fixture.cases[caseName];
  if (recorded === undefined) {
    throw new Error(
      `No case "${caseName}" in ${FIXTURE_PATH}. ` +
        `Add it to CASES in scripts/cicd/bootstrap_proposal_diff_fixture.py ` +
        `and regenerate with: ${fixture._regenerate}`,
    );
  }
  return recorded;
}

/** The redacted argument payload a proposal for this case would carry. */
export function redactedArguments(caseName: string): Record<string, unknown> {
  return redactedCase(caseName).redacted;
}
