"""Tests for gate_fan_out_advisory — flags a gate that duplicates every row.

AWS Composer acceptance run 2, R2-F17 (elspeth-5c0c09db31): asked to route
rows by ``amount > 500``, the planner authored a constant-condition gate whose
true and false routes both forked to BOTH sinks, so every row would have been
written twice.

The shape itself is legal and documented — ``condition: "True"`` with
``routes: {"true": "fork", "false": "fork"}`` is ELSPETH's fan-out idiom
(``pipeline_composer.md`` "Dual independent outputs"), it is generated by our
own authoring aids and repair scaffolds, and it appears in a dozen shipped
examples. So this is an ADVISORY, exactly like ``identity_node_advisory``: it
names the duplication and both remedies, and it never blocks.
"""

from __future__ import annotations

from pathlib import Path
from typing import cast
from unittest.mock import MagicMock, create_autospec, patch

from elspeth.core.dag.graph import ExecutionGraph
from elspeth.plugins.infrastructure.runtime_factory import PluginBundle
from elspeth.web.composer.state import (
    CompositionState,
    NodeSpec,
    OutputSpec,
    PipelineMetadata,
    SourceSpec,
)
from elspeth.web.config import WebSettings
from elspeth.web.execution.schemas import (
    CHECK_GATE_FAN_OUT_ADVISORY,
    VALIDATION_BLOCKING_CHECK_NAMES,
    VALIDATION_CHECK_NAMES,
)
from elspeth.web.execution.validation import (
    _find_gate_fan_out_advisories,
    validate_pipeline_for_trained_operator,
)

# ── Fixture builders ────────────────────────────────────────────────────


def _gate(
    node_id: str = "split",
    *,
    condition: str = "True",
    routes: dict[str, str] | None = None,
    fork_to: tuple[str, ...] | None = ("high_value", "standard"),
    input_field: str = "rows",
) -> NodeSpec:
    return NodeSpec(
        id=node_id,
        node_type="gate",
        plugin=None,
        input=input_field,
        on_success=None,
        on_error=None,
        options={},
        condition=condition,
        routes={"true": "fork", "false": "fork"} if routes is None else routes,
        fork_to=fork_to,
        branches=None,
        policy=None,
        merge=None,
    )


def _transform(node_id: str, input_field: str, on_success: str) -> NodeSpec:
    return NodeSpec(
        id=node_id,
        node_type="transform",
        plugin="value_transform",
        input=input_field,
        on_success=on_success,
        on_error="discard",
        options={"operations": [{"target": "x", "expression": "1"}]},
        condition=None,
        routes=None,
        fork_to=None,
        branches=None,
        policy=None,
        merge=None,
    )


def _coalesce(node_id: str, branches: dict[str, str], on_success: str) -> NodeSpec:
    return NodeSpec(
        id=node_id,
        node_type="coalesce",
        plugin=None,
        input=next(iter(branches.values())),
        on_success=on_success,
        on_error=None,
        options={},
        condition=None,
        routes=None,
        fork_to=None,
        branches=branches,
        policy="require_all",
        merge="nested",
    )


def _sink(name: str, data_dir: str | None = None) -> OutputSpec:
    path = "out.json" if data_dir is None else f"{data_dir}/outputs/test-session/{name}.json"
    return OutputSpec(
        name=name,
        plugin="json",
        options={"path": path, "schema": {"mode": "observed"}},
        on_write_failure="discard",
    )


def _state(
    nodes: tuple[NodeSpec, ...],
    outputs: tuple[OutputSpec, ...],
    source: SourceSpec | None = None,
) -> CompositionState:
    return CompositionState(
        source=source
        or SourceSpec(
            plugin="csv",
            on_success="rows",
            options={"path": "in.csv"},
            on_validation_failure="discard",
        ),
        nodes=nodes,
        edges=(),
        outputs=outputs,
        metadata=PipelineMetadata(),
        version=1,
    )


# ── Check-name registration ─────────────────────────────────────────────


def test_check_name_is_registered_and_non_blocking() -> None:
    """The name is the public contract; blocking membership is the whole point."""
    assert CHECK_GATE_FAN_OUT_ADVISORY == "gate_fan_out_advisory"
    assert CHECK_GATE_FAN_OUT_ADVISORY in VALIDATION_CHECK_NAMES
    assert CHECK_GATE_FAN_OUT_ADVISORY not in VALIDATION_BLOCKING_CHECK_NAMES


# ── Detection ───────────────────────────────────────────────────────────


def test_constant_gate_forking_to_two_terminal_sinks_is_flagged() -> None:
    """The R2-F17 shape: no decision, no per-branch work, two sinks written."""
    state = _state(
        nodes=(_gate(),),
        outputs=(_sink("high_value"), _sink("standard")),
    )

    findings = _find_gate_fan_out_advisories(state)

    assert [(finding.node_id, finding.destinations) for finding in findings] == [
        ("split", ("high_value", "standard")),
    ]
    assert findings[0].condition == "True"


def test_per_branch_transforms_are_differentiated_work_and_are_not_flagged() -> None:
    """The documented "dual independent outputs" macro: each branch does its own work."""
    state = _state(
        nodes=(
            _gate(fork_to=("branch_a", "branch_b")),
            _transform("summarise", "branch_a", "high_value"),
            _transform("detail", "branch_b", "standard"),
        ),
        outputs=(_sink("high_value"), _sink("standard")),
    )

    assert _find_gate_fan_out_advisories(state) == []


def test_branches_that_rejoin_a_barrier_are_not_flagged() -> None:
    """A fork that coalesces is fan-out with a rejoin — nothing is duplicated at a sink."""
    state = _state(
        nodes=(
            _gate(fork_to=("branch_a", "branch_b")),
            _coalesce("merge", {"branch_a": "branch_a", "branch_b": "branch_b"}, "merged"),
            _transform("emit", "merged", "high_value"),
        ),
        outputs=(_sink("high_value"),),
    )

    assert _find_gate_fan_out_advisories(state) == []


def test_a_real_condition_is_never_flagged() -> None:
    """A gate that reads the row makes a decision — that is the shape we WANT."""
    state = _state(
        nodes=(_gate(condition="row['amount'] > 500", routes={"true": "high_value", "false": "standard"}, fork_to=None),),
        outputs=(_sink("high_value"), _sink("standard")),
    )

    assert _find_gate_fan_out_advisories(state) == []


def test_single_destination_is_not_a_duplication() -> None:
    """``routes: {'true': out, 'false': out}`` is the canonical "everything to one sink" gate."""
    state = _state(
        nodes=(_gate(routes={"true": "standard", "false": "standard"}, fork_to=None),),
        outputs=(_sink("standard"),),
    )

    assert _find_gate_fan_out_advisories(state) == []


def test_routes_with_differing_destinations_are_not_flagged() -> None:
    """Even under a constant condition, distinct destinations are not a double-write."""
    state = _state(
        nodes=(_gate(routes={"true": "high_value", "false": "standard"}, fork_to=None),),
        outputs=(_sink("high_value"), _sink("standard")),
    )

    assert _find_gate_fan_out_advisories(state) == []


# ── Integration — wired into validate_pipeline_for_trained_operator() ────


def _make_settings(data_dir: str = "/tmp/test_data") -> WebSettings:
    return WebSettings(
        data_dir=Path(data_dir),
        composer_max_composition_turns=10,
        composer_max_discovery_turns=5,
        composer_timeout_seconds=30.0,
        composer_rate_limit_per_minute=60,
        shareable_link_signing_key=b"\x00" * 32,
    )


def _allowlisted_source(data_dir: str = "/tmp/test_data") -> SourceSpec:
    return SourceSpec(
        plugin="csv",
        on_success="rows",
        options={"path": f"{data_dir}/blobs/test-session/in.csv"},
        on_validation_failure="discard",
    )


class _YamlGeneratorDouble:
    def generate_yaml(self, state: CompositionState) -> str:
        return "source:\n  plugin: csv_source\n  options: {}"


def _runtime_bundle_double() -> PluginBundle:
    return cast(PluginBundle, create_autospec(PluginBundle, instance=True))


def _runtime_graph_double() -> MagicMock:
    graph = cast(MagicMock, create_autospec(ExecutionGraph, instance=True))
    graph.validation_warnings = ()
    return graph


@patch("elspeth.web.execution.validation.assemble_and_validate_pipeline_config")
@patch("elspeth.web.execution.validation.load_settings_from_yaml_string")
@patch("elspeth.web.execution.validation.instantiate_runtime_plugins")
@patch("elspeth.web.execution.validation.build_runtime_graph")
def test_advisory_is_emitted_without_blocking_the_run(
    mock_build_graph: MagicMock,
    mock_instantiate: MagicMock,
    mock_load: MagicMock,
    mock_assemble: MagicMock,
) -> None:
    """The whole point: the author is told, and the pipeline still runs."""
    mock_load.return_value = object()
    mock_instantiate.return_value = _runtime_bundle_double()
    mock_build_graph.return_value = _runtime_graph_double()
    mock_assemble.return_value = object()

    state = _state(
        source=_allowlisted_source(),
        nodes=(_gate(),),
        outputs=(_sink("high_value", "/tmp/test_data"), _sink("standard", "/tmp/test_data")),
    )
    result = validate_pipeline_for_trained_operator(state, _make_settings(), _YamlGeneratorDouble(), session_id="test-session")

    assert result.is_valid is True, "The advisory must never block a legal fan-out"
    advisories = [check for check in result.checks if check.name == CHECK_GATE_FAN_OUT_ADVISORY]
    assert len(advisories) == 1
    assert advisories[0].passed is True
    assert tuple(advisories[0].affected_nodes) == ("split",)
    detail = advisories[0].detail
    assert "split" in detail
    assert "high_value" in detail
    assert "standard" in detail
    # Both remedies must be named — the shape is legitimate fan-out OR a
    # missing condition, and the author is the only one who knows which.
    assert "Every row" in detail
    assert "fan-out" in detail
    assert "condition" in detail
