"""Multi-query ``required_input_fields`` contract at the plugin layer.

In multi-query mode each query renders with ``row`` bound to a synthetic
context (``QuerySpec.build_template_context``): its ``input_fields`` variables
plus ``source_row``. The ROW COLUMNS a query reads are therefore its
``input_fields`` VALUES and any second-level ``row.source_row.<column>``
reference — never the ``row.<variable>`` names its template interpolates.

* Finding #9 (elspeth-a10d15055b): with ``required_input_fields`` declared, a
  query column outside that declaration validated green and then failed every
  row at render with ``template_context_failed``.
* Finding #10: with ``required_input_fields`` undeclared, the suggested repair
  listed template variable names (and ``source_row``) as row columns, so
  applying it produced a blocking ``schema_contract_violation``.
"""

from __future__ import annotations

import json
import re
from typing import Any

import pytest
from pydantic import ValidationError

from elspeth.contracts.schema import SchemaConfig
from elspeth.plugins.transforms.llm.base import LLMConfig, multi_query_generated_input_conflicts, multi_query_source_row_columns
from elspeth.plugins.transforms.llm.multi_query import resolve_queries

_OBSERVED_SCHEMA = SchemaConfig.from_dict({"mode": "observed"})


@pytest.mark.parametrize("list_form", [False, True])
@pytest.mark.parametrize(
    "field",
    [
        "good_colour_pair_answer",
        "approximate_hex_answer",
        "good_colour_pair_reply",
        "good_colour_pair_reply_usage",
        "good_colour_pair_reply_model",
    ],
)
def test_generated_fields_cannot_be_required_inputs(field: str, list_form: bool) -> None:
    queries = {
        name: {
            "input_fields": {"shade": "colour"},
            "template": "{{ row.shade }}",
            "output_fields": [{"suffix": "answer", "type": "string"}],
        }
        for name in ("good_colour_pair", "approximate_hex")
    }
    with pytest.raises(ValidationError, match="generated by this node but also required as input"):
        LLMConfig(
            provider="azure",
            response_field="reply",
            queries=[{"name": name, **entry} for name, entry in queries.items()] if list_form else queries,
            required_input_fields=["colour", field],
            schema_config=_OBSERVED_SCHEMA,
        )


@pytest.mark.parametrize("consumer", ["alias", "source_row", "schema", "image", "image_format"])
def test_generated_fields_rejected_for_every_input_path_even_with_opt_out(consumer: str) -> None:
    options: dict[str, Any] = {
        "provider": "azure",
        "schema": {"mode": "observed"},
        "required_input_fields": [],
        "queries": {
            "classify": {
                "input_fields": {"text": "body"},
                "template": "{{ row.text }}",
                "output_fields": [{"suffix": "answer", "type": "string"}],
            }
        },
    }
    if consumer == "alias":
        options["queries"]["classify"]["input_fields"]["text"] = "classify_answer"
    elif consumer == "source_row":
        options["queries"]["classify"]["template"] = "{{ row.source_row['classify_answer'] }}"
    elif consumer == "schema":
        options["schema"]["required_fields"] = ["classify_answer"]
    elif consumer == "image":
        options["image_inputs"] = [{"field": "classify_answer", "format": "png"}]
    else:
        options["image_inputs"] = [{"field": "photo", "format_field": "classify_answer"}]
    with pytest.raises(ValidationError, match="generated by this node but also required as input"):
        LLMConfig.model_validate(options)


def test_generated_fields_in_schema_fields_are_not_required_input_declarations() -> None:
    config = LLMConfig.model_validate(
        {
            "provider": "azure",
            "required_input_fields": ["colour", "extra"],
            "schema": {"mode": "flexible", "fields": ["colour: str", "classify_answer: str"]},
            "queries": {
                "classify": {
                    "input_fields": {"classify_answer": "colour"},
                    "template": "{{ row.classify_answer }}",
                    "output_fields": [{"suffix": "answer", "type": "string"}],
                }
            },
        }
    )
    assert config.declared_input_fields == frozenset({"colour", "extra"})


def test_shared_generated_input_helper_uses_alias_values_and_returns_sorted_conflicts() -> None:
    config = _multi(
        {
            "classify": {
                "input_fields": {"classify_answer": "body"},
                "template": "{{ row.classify_answer }}",
                "output_fields": [{"suffix": "answer", "type": "string"}],
            }
        },
        required=["body", "extra"],
    )
    assert config.queries is not None
    specs = resolve_queries(config.queries)
    assert multi_query_generated_input_conflicts(specs, "reply", ["body", "extra"]) == ()
    assert multi_query_generated_input_conflicts(specs, "reply", ["classify_reply_usage", "classify_answer", "classify_answer"]) == (
        "classify_answer",
        "classify_reply_usage",
    )


def test_single_mode_input_contract_is_unchanged_by_multi_query_guard() -> None:
    config = LLMConfig.model_validate(
        {
            "provider": "azure",
            "prompt_template": "{{ row.classify_answer }}",
            "required_input_fields": ["classify_answer", "extra"],
            "schema": {"mode": "observed"},
            "output_fields": [{"suffix": "answer", "type": "string"}],
        }
    )
    assert config.declared_input_fields == frozenset({"classify_answer", "extra"})


def _multi(
    queries: dict[str, Any],
    *,
    required: list[str] | None,
    template: str = "Assess",
    image_inputs: list[dict[str, str]] | None = None,
) -> LLMConfig:
    kwargs: dict[str, Any] = {
        "provider": "azure",
        "prompt_template": template,
        "schema_config": _OBSERVED_SCHEMA,
        "queries": queries,
    }
    if required is not None:
        kwargs["required_input_fields"] = required
    if image_inputs is not None:
        kwargs["image_inputs"] = image_inputs
    return LLMConfig(**kwargs)


def _suggested(exc: pytest.ExceptionInfo[ValidationError]) -> list[str]:
    match = re.search(r"options\.required_input_fields: (\[[^\]]*\])  # Require these fields", str(exc.value))
    assert match is not None, str(exc.value)
    return json.loads(match.group(1))


class TestDeclaredMultiQueryColumnsMustBeCovered:
    """Finding #9 — the plugin layer."""

    def test_input_fields_value_outside_declaration_is_rejected(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "missing_col"}, "template": "Classify {{ row.text }}"}}, required=["title"])
        message = str(exc_info.value)
        assert "Query 'classify' reads row column 'missing_col'" in message
        assert "it declares 'title'" in message

    def test_source_row_column_outside_declaration_is_rejected(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }} {{ row.source_row.title }}"}},
                required=["body"],
            )
        assert "reads row column 'title'" in str(exc_info.value)

    def test_node_level_template_source_row_column_is_checked_for_queries_that_fall_back_to_it(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"classify": {"input_fields": {"text": "body"}}}, required=["body"], template="{{ row.text }} {{ row.source_row['title'] }}"
            )
        assert "reads row column 'title'" in str(exc_info.value)

    def test_source_row_get_call_names_its_literal_column(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row.source_row.get('title') }}"}},
                required=["body"],
            )
        assert "reads row column 'title'" in str(exc_info.value)

    def test_covered_columns_are_accepted(self) -> None:
        config = _multi(
            {"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }} {{ row.source_row.title }}"}},
            required=["body", "title"],
        )
        assert config.declared_input_fields == frozenset({"body", "title"})

    def test_template_variable_names_need_no_declaration(self) -> None:
        """``row.text`` is a query variable, not a column: declaring only the column suffices."""
        config = _multi({"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }}"}}, required=["body"])
        assert config.required_input_fields == ["body"]

    def test_explicit_opt_out_is_still_accepted(self) -> None:
        config = _multi({"classify": {"input_fields": {"text": "missing_col"}, "template": "Classify {{ row.text }}"}}, required=[])
        assert config.required_input_fields == []


@pytest.mark.parametrize("consumed_by", ["required", "query_alias", "source_row", "schema_required", "image"])
def test_multi_query_rejects_its_own_generated_field_as_input(consumed_by: str) -> None:
    options: dict[str, Any] = {
        "provider": "azure",
        "schema": {"mode": "observed"},
        "required_input_fields": ["body"],
        "prompt_template": "{{ row.text }}",
        "queries": {
            "classify": {
                "input_fields": {"text": "body"},
                "output_fields": [{"suffix": "answer", "type": "string"}],
            }
        },
    }
    if consumed_by == "required":
        options["required_input_fields"].append("classify_answer")
    elif consumed_by == "query_alias":
        options["queries"]["classify"]["input_fields"]["text"] = "classify_answer"
    elif consumed_by == "source_row":
        options["queries"]["classify"]["template"] = "{{ row.source_row.classify_answer }}"
    elif consumed_by == "schema_required":
        options["schema"]["required_fields"] = ["classify_answer"]
    else:
        options["image_inputs"] = [{"field": "classify_answer", "format": "png"}]
    with pytest.raises(ValidationError, match="generated by this node but also required as input"):
        LLMConfig.model_validate(options)

    def test_bracket_header_column_is_covered_by_its_canonical_declaration(self) -> None:
        config = _multi(
            {"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row.source_row['Original Header'] }}"}},
            required=["body", "original_header"],
        )
        assert config.required_input_fields == ["body", "original_header"]

    def test_unused_node_level_template_is_not_read(self) -> None:
        """A node-level prompt_template no query falls back to never renders."""
        config = _multi(
            {"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }}"}},
            required=["body"],
            template="Dead slot {{ row.source_row.never_rendered }}",
        )
        assert config.required_input_fields == ["body"]

    def test_subscripted_source_row_column_outside_declaration_is_rejected(self) -> None:
        """``row['source_row']['<column>']`` reads the row as surely as ``row.source_row.<column>``."""
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row['source_row']['title'] }}"}},
                required=["body"],
            )
        assert "reads row column 'title'" in str(exc_info.value)

    def test_image_input_columns_cover_query_input_fields(self) -> None:
        """An ``input_fields`` value is read in the parent from the full row, so ``image_inputs`` columns cover it."""
        config = _multi(
            {
                "describe": {
                    "input_fields": {"text": "body", "picture": "photo", "mime": "photo_mime"},
                    "template": "{{ row.text }} {{ row.picture }} {{ row.mime }}",
                }
            },
            required=["body"],
            image_inputs=[{"field": "photo", "format_field": "photo_mime"}],
        )
        assert config.declared_input_fields == frozenset({"body", "photo", "photo_mime"})

    def test_a_source_row_read_must_be_in_required_input_fields_itself(self) -> None:
        """The template's ``row.source_row`` holds only ``required_input_fields`` (ADR-051): an image column is not in it.

        Admitting it would validate green and fail every row at render with an
        undeclared read, so configuration refuses it with the shared message.
        """
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"describe": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row.source_row.photo_mime }}"}},
                required=["body"],
                image_inputs=[{"field": "photo", "format_field": "photo_mime"}],
            )
        assert "Query 'describe' reads row column 'photo_mime' through its input_fields values or 'row.source_row'" in str(exc_info.value)


class TestSourceRowReadsWithoutAColumnName:
    """A computed key through ``row.source_row`` fails closed at configuration, as through ``row`` (S0 fix round 1).

    The dynamic-access gate looks at ``row`` and, in a query, at ``row.source_row``
    too: a computed key there names no column, so configuration refuses it early.
    A whole ``source_row`` used as a value is not a configuration question: at
    render it holds only the declared fields (ADR-051).
    """

    @pytest.mark.parametrize(
        ("template", "kind"),
        [
            ("{{ row.text }} {% for k in row.source_row %}{{ row.source_row[k] }}{% endfor %}", "item via row[expr]"),
            ("{{ row.text }} {{ row.source_row.get(row.text) }}", "get via row.get(expr)"),
            ("{% set s = row.source_row %}{{ row.text }} {{ s[row.text] }}", "item via row[expr]"),
        ],
    )
    def test_declared_contract_cannot_vouch_for_the_read(self, template: str, kind: str) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}, "template": template}}, required=["body"])
        assert f"dynamic row field access ({kind})" in str(exc_info.value)

    @pytest.mark.parametrize(
        "template",
        [
            "{{ row.text }} {{ row.source_row | dictsort }}",
            "{{ row.text }} {{ dict(row['source_row']) }}",
            "{% macro m() %}{{ varargs[0] | dictsort }}{% endmacro %}{{ row.text }} {{ m(row.source_row) }}",
            "{% macro m() %}{{ kwargs.r | dictsort }}{% endmacro %}{{ row.text }} {{ m(r=row.source_row) }}",
        ],
    )
    def test_a_whole_source_row_value_is_admitted_and_projected_at_render(self, template: str) -> None:
        config = _multi({"classify": {"input_fields": {"text": "body"}, "template": template}}, required=["body"])
        assert config.required_input_fields == ["body"]

    def test_explicit_opt_out_admits_it(self) -> None:
        config = _multi(
            {"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row.source_row | dictsort }}"}}, required=[]
        )
        assert config.required_input_fields == []


class TestSourceRowColumnExtraction:
    """``multi_query_source_row_columns`` reads every literal ``source_row`` spelling and nothing else."""

    def test_every_literal_spelling_is_read(self) -> None:
        template = (
            "{{ row.source_row.a }} {{ row.source_row['b'] }} {{ row['source_row']['c'] }} "
            "{{ row['source_row'].d }} {{ row.source_row.get('e') }} {{ row['source_row'].get('f') }}"
        )
        assert multi_query_source_row_columns(template) == frozenset({"a", "b", "c", "d", "e", "f"})

    def test_the_get_method_query_variables_and_computed_keys_contribute_nothing(self) -> None:
        template = (
            "{{ row.text }} {{ row.source_row.get }} {{ row.source_row._data }} "
            "{{ row.source_row[key] }} {{ row['other']['x'] }} {{ row.source_row }}"
        )
        assert multi_query_source_row_columns(template) == frozenset()

    def test_a_method_name_is_a_column_read_and_a_reserved_name_is_not(self) -> None:
        """``row.source_row`` holds fields and one method, as a single-query ``row`` does (G3).

        ``keys`` reads a column; ``to_dict`` and ``contract`` are reserved names,
        which ``_validate_template_row_access`` refuses on every surface before any
        column check, so they are never columns to declare.
        """
        template = "{{ row.source_row.to_dict() }} {{ row['source_row'].contract }} {{ row.source_row.keys }}"
        assert multi_query_source_row_columns(template) == frozenset({"keys"})

    @pytest.mark.parametrize(
        "template",
        [
            pytest.param("{{ row.source_row | attr('x') }}", id="attr"),
            pytest.param("{{ [row.source_row] | map(attribute='x') | list }}", id="map-attribute"),
            pytest.param("{{ [row.source_row] | map('attr', 'x') | list }}", id="map-attr"),
            pytest.param("{{ [row.source_row] | selectattr('x') | list }}", id="selectattr"),
            pytest.param("{{ [row.source_row] | sort(attribute='x') | list }}", id="sort-attribute"),
            pytest.param("{{ [row.source_row] | join(',', attribute='x') }}", id="join-attribute"),
            pytest.param("{{ [row.source_row] | groupby('x') | list }}", id="groupby"),
            pytest.param("{{ [row.source_row] | sum(attribute='x') }}", id="sum-attribute"),
            pytest.param("{% set s = row.source_row %}{{ s.x }}", id="an-alias-of-the-row"),
        ],
    )
    def test_an_attribute_resolving_filter_reads_a_column(self, template: str) -> None:
        """The column analysis is the single-query field analysis pointed at ``row.source_row``.

        A narrower walk of its own once missed these forms, so an undeclared
        column read through them validated and failed every row
        (review-G3-template-api-r2 F2).
        """
        assert multi_query_source_row_columns(template) == frozenset({"x"})

    @pytest.mark.parametrize(
        "form",
        [
            pytest.param("{{ row.source_row | attr('note') }}", id="attr"),
            pytest.param("{{ [row.source_row] | map(attribute='note') | list }}", id="map-attribute"),
            pytest.param("{{ [row.source_row] | selectattr('note') | list }}", id="selectattr"),
            pytest.param("{{ [row.source_row] | sum(attribute='note') }}", id="sum-attribute"),
        ],
    )
    def test_an_undeclared_column_read_through_a_filter_is_refused(self, form: str) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} " + form}}, required=["body"])
        assert "Query 'classify' reads row column 'note' through its input_fields values or 'row.source_row'" in str(exc_info.value)


class TestQueryVariablesExcludeSourceRowReads:
    """A method on a column's value is not a query variable (review-G3-template-api-r3 F4).

    The binding check judges ``row.<variable>`` against the query's input_fields;
    a read through ``row.source_row`` is a column read and names no variable.
    """

    @pytest.mark.parametrize(
        "form",
        [
            pytest.param("{{ row.source_row.get('body', '').upper() }}", id="get-with-default"),
            pytest.param("{{ row.source_row.get('body').upper() }}", id="get"),
            pytest.param("{{ row.source_row.body.upper() }}", id="attribute"),
            pytest.param("{{ row['source_row']['body'].upper() }}", id="item"),
        ],
    )
    def test_a_method_on_a_column_value_is_admitted(self, form: str) -> None:
        config = _multi({"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} " + form}}, required=["body"])
        assert config.required_input_fields == ["body"]

    def test_an_unbound_variable_is_still_refused(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}, "template": "{{ row.text }} {{ row.other }}"}}, required=["body"])
        assert "references 'other' under 'row', but this query's input_fields binds only 'text'" in str(exc_info.value)


class TestUndeclaredMultiQuerySuggestionNamesColumnsOnly:
    """Finding #10 — the repair suggestion must list row columns, never query variables."""

    def test_suggestion_is_the_input_fields_values(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }}"}}, required=None)
        assert _suggested(exc_info) == ["body"]

    def test_suggestion_adds_source_row_columns_not_source_row(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi(
                {"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }} {{ row.source_row.title }}"}},
                required=None,
            )
        assert _suggested(exc_info) == ["body", "title"]

    def test_suggestion_ignores_variables_in_the_node_level_template(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}}}, required=None, template="Classify {{ row.text }}")
        assert _suggested(exc_info) == ["body"]

    def test_suggestion_reads_source_row_columns_of_the_node_level_template_a_query_falls_back_to(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            _multi({"classify": {"input_fields": {"text": "body"}}}, required=None, template="{{ row.text }} {{ row.source_row.title }}")
        assert _suggested(exc_info) == ["body", "title"]

    def test_applying_the_suggestion_validates(self) -> None:
        queries = {"classify": {"input_fields": {"text": "body"}, "template": "Classify {{ row.text }} {{ row.source_row.title }}"}}
        with pytest.raises(ValidationError) as exc_info:
            _multi(queries, required=None)
        config = _multi(queries, required=_suggested(exc_info))
        assert config.declared_input_fields == frozenset({"body", "title"})

    def test_single_prompt_suggestion_is_unchanged(self) -> None:
        with pytest.raises(ValidationError) as exc_info:
            LLMConfig(provider="azure", prompt_template="Classify {{ row.body }}", schema_config=_OBSERVED_SCHEMA)
        assert "LLM prompt_template references row fields ['body'] but options.required_input_fields is not declared." in str(
            exc_info.value
        )
        assert _suggested(exc_info) == ["body"]


def test_all_overrides_need_no_dead_node_template() -> None:
    config = LLMConfig(
        provider="azure",
        schema_config=_OBSERVED_SCHEMA,
        required_input_fields=["colour"],
        queries={"decorate": {"input_fields": {"colour": "colour"}, "template": "Decorate {{ row.colour }}"}},
    )
    assert config.prompt_template is None


def test_missing_effective_query_template_rejected() -> None:
    with pytest.raises(ValidationError, match="prompt_template") as exc_info:
        LLMConfig(
            provider="azure",
            schema_config=_OBSERVED_SCHEMA,
            required_input_fields=[],
            queries={"decorate": {"input_fields": {"colour": "colour"}}},
        )
    assert exc_info.value.errors()[0]["loc"] == ("prompt_template",)
