"""Pin the frontend's redacted-argument fixture to the live redactor.

pytest cannot see the frontend, and that gap is how elspeth-b1c14dd3c2
shipped: four arms of the proposal-diff projection read the ``patch``
argument as a plain object, the redactor had long since replaced it with a
summary string, and the frontend tests hand-built the object shape so all four
stayed green while none of them could run on the live path.

This test closes the loop from the side that CAN see the producer. The
frontend reads its inputs from
``src/elspeth/web/frontend/src/test/fixtures/redacted-tool-arguments.json``;
here every recorded ``redacted`` payload is re-derived from its ``arguments``
through :func:`redact_tool_call_arguments` and compared. A change to the
redaction grammar therefore fails a Python test naming the regeneration
script, instead of silently invalidating a frontend suite that keeps passing.

The fixture is generated by ``scripts/cicd/bootstrap_proposal_diff_fixture.py``,
which owns the case list.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from elspeth.web.composer.redaction import redact_tool_call_arguments
from elspeth.web.composer.redaction_telemetry import NoopRedactionTelemetry

# ``__file__`` is ``<project_root>/tests/unit/web/composer/<this file>``.
PROJECT_ROOT = Path(__file__).resolve().parents[4]
FIXTURE_PATH = PROJECT_ROOT / "src" / "elspeth" / "web" / "frontend" / "src" / "test" / "fixtures" / "redacted-tool-arguments.json"
REGENERATE_HINT = (
    "Run '.venv/bin/python scripts/cicd/bootstrap_proposal_diff_fixture.py --write' "
    "to regenerate, then review the diff AND the frontend tests that read the "
    "changed cases (src/elspeth/web/frontend/src/**/*.test.ts*) before merging: "
    "a grammar change here can make a frontend projection unreachable without "
    "reddening any frontend test."
)


def _load_fixture() -> dict[str, Any]:
    assert FIXTURE_PATH.is_file(), f"Missing {FIXTURE_PATH}. {REGENERATE_HINT}"
    loaded = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict), "fixture root must be an object"
    return loaded


def _cases() -> dict[str, Any]:
    cases = _load_fixture()["cases"]
    assert isinstance(cases, dict) and cases, "fixture must record at least one case"
    return cases


@pytest.mark.parametrize("case_name", sorted(_cases()))
def test_recorded_redaction_matches_the_live_redactor(case_name: str) -> None:
    """Each recorded payload is what the redactor produces today."""
    case = _cases()[case_name]
    actual = redact_tool_call_arguments(case["tool"], case["arguments"], telemetry=NoopRedactionTelemetry())

    # Round-trip through JSON so the comparison is against the wire form the
    # frontend actually receives: the redactor returns str subclasses
    # (_TrustedRedactionSummary) that compare equal to str but are not what
    # crosses the HTTP boundary.
    assert json.loads(json.dumps(actual)) == case["redacted"], (
        f"Redaction drift for fixture case '{case_name}' ({case['tool']}). {REGENERATE_HINT}"
    )


def test_fixture_covers_every_tool_the_proposal_diff_projects() -> None:
    """The projection's tool arms each have at least one recorded payload.

    ProposalDiff.tsx switches on the tool name; an arm with no recorded
    payload is an arm whose live shape nothing verifies, which is exactly the state
    elspeth-b1c14dd3c2 was filed for. `set_source`, `clear_source`,
    `remove_node`, `upsert_edge`, `remove_edge` and `remove_output` are
    deliberately absent: they carry no summarized argument, so their live
    shape is the shape the frontend already builds.
    """
    tools_recorded = {case["tool"] for case in _cases().values()}

    assert {
        "patch_source_options",
        "patch_node_options",
        "patch_output_options",
        "set_metadata",
        "set_pipeline",
    } <= tools_recorded


def test_every_summarized_argument_is_recorded_as_a_string() -> None:
    """The consumer-facing fact this fixture exists to pin.

    `patch` on the three patch_*_options tools and on set_metadata is a
    STRING after redaction, never a mapping. A frontend reader that treats it
    as a mapping is dead code, and this is the assertion that says so in the
    language that can see the producer.
    """
    for case_name, case in _cases().items():
        if case["tool"] not in {
            "patch_source_options",
            "patch_node_options",
            "patch_output_options",
            "set_metadata",
        }:
            continue
        patch = case["redacted"]["patch"]
        assert isinstance(patch, str), f"Fixture case '{case_name}' records a non-string patch ({type(patch).__name__}). {REGENERATE_HINT}"
