"""Pin the frontend's redacted-argument fixture to the live redactor.

pytest cannot see the frontend, and that gap is how elspeth-b1c14dd3c2
shipped: four arms of the proposal-diff projection read the ``patch``
argument as a plain object, the redactor had long since replaced it with a
summary string, and the frontend tests hand-built the object shape so all four
stayed green while none of them could run on the live path.

This test closes the loop from the side that CAN see the producer. The
frontend reads its inputs from
``src/elspeth/web/frontend/src/test/fixtures/redacted-tool-arguments.json``;
here every recorded ``redacted`` payload is re-derived from its ``arguments``
through :func:`redact_tool_call_arguments` and compared. A change to the
redaction grammar therefore fails a Python test naming the regeneration
script, instead of silently invalidating a frontend suite that keeps passing.

The fixture is generated by ``scripts/cicd/bootstrap_proposal_diff_fixture.py``,
which owns the case list.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from elspeth.web.composer.redaction import (
    MANIFEST,
    ToolRedaction,
    _SensitiveMarker,
    redact_tool_call_arguments,
    walk_model_schema,
)
from elspeth.web.composer.redaction_telemetry import NoopRedactionTelemetry

# ``__file__`` is ``<project_root>/tests/unit/web/composer/<this file>``.
PROJECT_ROOT = Path(__file__).resolve().parents[4]
FIXTURE_PATH = PROJECT_ROOT / "src" / "elspeth" / "web" / "frontend" / "src" / "test" / "fixtures" / "redacted-tool-arguments.json"
REGENERATE_HINT = (
    "Run '.venv/bin/python scripts/cicd/bootstrap_proposal_diff_fixture.py --write' "
    "to regenerate, then review the diff AND the frontend tests that read the "
    "changed cases (src/elspeth/web/frontend/src/**/*.test.ts*) before merging: "
    "a grammar change here can make a frontend projection unreachable without "
    "reddening any frontend test."
)


def _load_fixture() -> dict[str, Any]:
    assert FIXTURE_PATH.is_file(), f"Missing {FIXTURE_PATH}. {REGENERATE_HINT}"
    loaded = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict), "fixture root must be an object"
    return loaded


def _cases() -> dict[str, Any]:
    cases = _load_fixture()["cases"]
    assert isinstance(cases, dict) and cases, "fixture must record at least one case"
    return cases


@pytest.mark.parametrize("case_name", sorted(_cases()))
def test_recorded_redaction_matches_the_live_redactor(case_name: str) -> None:
    """Each recorded payload is what the redactor produces today."""
    case = _cases()[case_name]
    actual = redact_tool_call_arguments(case["tool"], case["arguments"], telemetry=NoopRedactionTelemetry())

    # Round-trip through JSON so the comparison is against the wire form the
    # frontend actually receives: the redactor returns str subclasses
    # (_TrustedRedactionSummary) that compare equal to str but are not what
    # crosses the HTTP boundary.
    assert json.loads(json.dumps(actual)) == case["redacted"], (
        f"Redaction drift for fixture case '{case_name}' ({case['tool']}). {REGENERATE_HINT}"
    )


# The tools ProposalDiff.tsx's `switch (toolName)` projects. Hand-maintained:
# the frontend switch is the authority and Python cannot read it, so a new arm
# there means a line here. Everything ELSE about coverage is derived below
# rather than asserted, because the first version of this guard hard-coded
# which tools "carry no summarized argument" and was wrong about `set_source`
# — a coverage claim resting on an untrue statement about the producer, which
# is the very defect class this file exists to prevent.
PROJECTED_TOOLS = frozenset(
    {
        "set_source",
        "clear_source",
        "upsert_node",
        "remove_node",
        "upsert_edge",
        "remove_edge",
        "set_output",
        "remove_output",
        "set_metadata",
        "patch_source_options",
        "patch_node_options",
        "patch_output_options",
        "set_pipeline",
    }
)


def _summarizes_an_argument(entry: ToolRedaction) -> bool:
    """Does this manifest entry replace any ARGUMENT with a summary?

    Mirrors the two manifest shapes (``ToolRedaction`` invariant: exactly one).
    Deliberately argument-only — a tool that summarizes only its RESPONSE
    changes nothing about the payload the proposal card renders.
    """
    if entry.argument_model is not None:
        return any(
            any(isinstance(marker, _SensitiveMarker) for marker in node.metadata) for node in walk_model_schema(entry.argument_model)
        )
    assert entry.policy is not None  # ToolRedaction invariant
    return bool(entry.policy.sensitive_argument_keys)


def test_fixture_records_every_projected_tool_whose_arguments_are_summarized() -> None:
    """Coverage derived from the live MANIFEST, not from a hand-written list.

    A projected tool whose redaction summarizes an argument is a tool whose
    live payload differs from anything a frontend test would hand-build — the
    exact gap elspeth-b1c14dd3c2 was filed for. Which tools those are is read
    off the manifest here, so adding a Sensitive argument to any projected
    tool fails this test until the fixture records it.

    DO NOT replace ``must_record`` with a literal set, however obvious the
    membership looks today. The first version of this guard did exactly that
    and was wrong about ``set_source`` — the derivation is the point, because
    a guard that restates its authority instead of consulting it eventually
    lies about it. ``PROJECTED_TOOLS`` is the one hand-maintained input, and
    only because the frontend ``switch`` is its authority and Python cannot
    read it.

    KNOWN RESIDUE (elspeth-f491fca94e): because that one input is a
    transcription rather than a derivation, a tool absent from BOTH
    ``PROJECTED_TOOLS`` and the fixture is invisible here — most realistically
    a new frontend ``switch`` arm whose author never learns this frozenset
    exists. Measured: such an omission leaves every test in this file green.
    """
    tools_recorded = {case["tool"] for case in _cases().values()}
    must_record = {name for name, entry in MANIFEST.items() if name in PROJECTED_TOOLS and _summarizes_an_argument(entry)}

    assert must_record, "manifest introspection found nothing — the derivation is broken"
    missing = must_record - tools_recorded
    assert not missing, (
        f"Projected tools whose arguments are summarized but have no fixture case: {sorted(missing)}. Add them to CASES. {REGENERATE_HINT}"
    )


def test_uncovered_projected_tools_really_do_carry_no_summarized_argument() -> None:
    """The other half of the claim, made executable rather than asserted.

    A projected tool absent from the fixture is only safe to omit if its live
    argument shape is the shape a frontend test already builds — i.e. nothing
    is summarized. The original docstring asserted that about `set_source` and
    was wrong: `set_source.options` goes through the same
    ``_summarize_set_source_options`` as `upsert_node` and `set_output`.
    """
    tools_recorded = {case["tool"] for case in _cases().values()}
    omitted = PROJECTED_TOOLS - tools_recorded

    wrongly_omitted = {name for name in omitted if name in MANIFEST and _summarizes_an_argument(MANIFEST[name])}
    assert not wrongly_omitted, (
        f"These projected tools are absent from the fixture but DO summarize an "
        f"argument, so their live shape is unverified: {sorted(wrongly_omitted)}. "
        f"{REGENERATE_HINT}"
    )


def _key_order(value: Any) -> Any:
    """Recursively project a payload down to its key ORDER alone."""
    if isinstance(value, dict):
        return [(key, _key_order(inner)) for key, inner in value.items()]
    if isinstance(value, list):
        return [_key_order(item) for item in value]
    return None


@pytest.mark.parametrize("case_name", sorted(_cases()))
def test_recorded_payload_preserves_the_producers_key_order(case_name: str) -> None:
    """Key ORDER is fixture content, because the consumer depends on it.

    ``providedKeysDiffer`` walks ``Object.entries`` and, before this was
    caught, returned at the first differing key — so WHERE a summarized key
    sits among its siblings decided whether it was examined at all. On the
    wire ``plugin`` precedes ``options`` on a source and an output; sorted, it
    follows them. A sorted fixture therefore exercises a path the live payload
    never takes, and no equality assertion notices, because ``==`` on dicts
    ignores order.

    This is the assertion the ordinary drift test cannot make:
    ``test_recorded_redaction_matches_the_live_redactor`` compares parsed
    dicts and would stay green against a re-sorted fixture.
    """
    case = _cases()[case_name]
    actual = redact_tool_call_arguments(case["tool"], case["arguments"], telemetry=NoopRedactionTelemetry())

    assert _key_order(json.loads(json.dumps(actual))) == _key_order(case["redacted"]), (
        f"Key-order drift for fixture case '{case_name}'. The generator must NOT "
        f"sort keys — the frontend's short-circuit depends on the producer's own "
        f"order. {REGENERATE_HINT}"
    )


def test_projected_tools_all_exist_in_the_manifest() -> None:
    """PROJECTED_TOOLS is hand-maintained; catch a typo or a renamed tool."""
    unknown = PROJECTED_TOOLS - set(MANIFEST)
    assert not unknown, f"PROJECTED_TOOLS names tools absent from MANIFEST: {sorted(unknown)}"


def test_every_summarized_argument_is_recorded_as_a_string() -> None:
    """The consumer-facing fact this fixture exists to pin.

    `patch` on the three patch_*_options tools and on set_metadata is a
    STRING after redaction, never a mapping. A frontend reader that treats it
    as a mapping is dead code, and this is the assertion that says so in the
    language that can see the producer.

    `patch` may also be ABSENT — set_metadata called with no arguments
    redacts to ``{}``. Absent is a third state, distinct from both a mapping
    and a summary string, and a decoder that only handles strings has to
    survive it. What is asserted here is the narrow fact that matters: when
    `patch` is present it is a string, never a mapping.
    """
    summarized_patch_tools = {
        "patch_source_options",
        "patch_node_options",
        "patch_output_options",
        "set_metadata",
    }
    saw_absent_patch = False
    for case_name, case in _cases().items():
        if case["tool"] not in summarized_patch_tools:
            continue
        if "patch" not in case["redacted"]:
            saw_absent_patch = True
            continue
        patch = case["redacted"]["patch"]
        assert isinstance(patch, str), f"Fixture case '{case_name}' records a non-string patch ({type(patch).__name__}). {REGENERATE_HINT}"

    # Keep the absent-patch case in the corpus deliberately: it is the only
    # one that exercises `args.patch === undefined` on the consumer side.
    assert saw_absent_patch, f"Fixture no longer records a case with an absent `patch`. {REGENERATE_HINT}"
