"""Pin the frontend's redacted-argument fixture to the live redactor.

The missing producer-to-frontend contract is how elspeth-b1c14dd3c2
shipped: four arms of the proposal-diff projection read the ``patch``
argument as a plain object, the redactor had long since replaced it with a
summary string, and the frontend tests hand-built the object shape so all four
stayed green while none of them could run on the live path.

This test closes the loop from the side that CAN see the producer. The
frontend reads its inputs from
``src/elspeth/web/frontend/src/test/fixtures/redacted-tool-arguments.json``;
here every recorded ``redacted`` payload is re-derived from its ``arguments``
through :func:`redact_tool_call_arguments` and compared. A change to the
redaction grammar therefore fails a Python test naming the regeneration
script, instead of silently invalidating a frontend suite that keeps passing.

The fixture is generated by ``scripts/cicd/bootstrap_proposal_diff_fixture.py``,
which owns the case list. Python validates recorded tool names against the live
redaction manifest without requiring frontend dependencies. The provisioned
Vitest gate compares the parser bridge, runtime registry, exported tool names,
and this fixture; that gate owns frontend dispatch inventory parity.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from scripts.cicd import composer_frontend_wire as frontend

from elspeth.web.composer.proposals import build_tool_proposal_summary
from elspeth.web.composer.redaction import redact_tool_call_arguments
from elspeth.web.composer.redaction_telemetry import NoopRedactionTelemetry


def test_inline_proposal_generic_review_preserves_the_authored_presence() -> None:
    cases = frontend.fixture_cases()
    name = "set_pipeline_ambiguous_inline_omitted_metadata"
    assert name in cases, "Generic source review must use an actual producer fixture"
    case = cases[name]
    arguments = case["arguments"]
    assert "metadata" not in arguments
    assert arguments["source"]["description"] is None
    assert arguments["source"]["options"] == {}
    assert arguments["source"]["inline_blob"]["content"]
    actual = redact_tool_call_arguments(case["tool"], arguments, telemetry=NoopRedactionTelemetry())
    assert "metadata" not in actual
    assert actual["source"]["description"] is None
    assert json.loads(actual["source"]["options"])["entry_count"] == 0
    assert json.loads(json.dumps(actual)) == case["redacted"]
    summary = build_tool_proposal_summary(tool_name=case["tool"], arguments=arguments, redacted_arguments=actual)
    assert summary.summary == case["proposal_summary"]
    assert summary.summary == "Replace the pipeline with 1 input, 0 processing nodes, and 0 outputs."


@pytest.mark.parametrize("case_name", sorted(frontend.fixture_cases()))
def test_recorded_redaction_matches_the_live_redactor(case_name: str) -> None:
    """Each recorded payload is what the redactor produces today."""
    case = frontend.fixture_cases()[case_name]
    actual = redact_tool_call_arguments(case["tool"], case["arguments"], telemetry=NoopRedactionTelemetry())

    # Round-trip through JSON so the comparison is against the wire form the
    # frontend actually receives: the redactor returns str subclasses
    # (_TrustedRedactionSummary) that compare equal to str but are not what
    # crosses the HTTP boundary.
    assert json.loads(json.dumps(actual)) == case["redacted"], (
        f"Redaction drift for fixture case '{case_name}' ({case['tool']}). {frontend.REGENERATE_HINT}"
    )
    assert (
        build_tool_proposal_summary(tool_name=case["tool"], arguments=case["arguments"], redacted_arguments=actual).summary
        == case["proposal_summary"]
    )


def test_fixture_records_every_projected_tool_whose_arguments_are_summarized() -> None:
    """Coverage derived from the live MANIFEST, not from a hand-written list.

    A projected tool whose redaction summarizes an argument is a tool whose
    live payload differs from anything a frontend test would hand-build — the
    exact gap elspeth-b1c14dd3c2 was filed for. Which tools those are is read
    off the manifest here, so adding a Sensitive argument to any projected
    tool fails this test until the fixture records it.

    The fixture records frontend registry keys through the TypeScript parser
    bridge. Vitest owns their parity with live frontend dispatch; Python owns
    their coverage against the live redaction manifest.
    """
    rows = frontend.census_frontend_wire()
    assert any(row.fixture_required for row in rows.values()), "manifest introspection found nothing"
    missing = {name for name, row in rows.items() if row.missing_fixture}
    assert not missing, f"Summarized projected tools missing fixture cases: {sorted(missing)}. {frontend.REGENERATE_HINT}"


def test_uncovered_projected_tools_really_do_carry_no_summarized_argument() -> None:
    """The other half of the claim, made executable rather than asserted.

    A projected tool absent from the fixture is only safe to omit if its live
    argument shape is the shape a frontend test already builds — i.e. nothing
    is summarized. The original docstring asserted that about `set_source` and
    was wrong: `set_source.options` goes through the same
    ``_summarize_set_source_options`` as `upsert_node` and `set_output`.
    """
    rows = frontend.census_frontend_wire()
    wrongly_omitted = {name for name, row in rows.items() if row.missing_fixture}
    assert not wrongly_omitted, f"Summarized projected tools missing fixture cases: {sorted(wrongly_omitted)}"


def _key_order(value: Any) -> Any:
    """Recursively project a payload down to its key ORDER alone."""
    if isinstance(value, dict):
        return [(key, _key_order(inner)) for key, inner in value.items()]
    if isinstance(value, list):
        return [_key_order(item) for item in value]
    return None


@pytest.mark.parametrize("case_name", sorted(frontend.fixture_cases()))
def test_recorded_payload_preserves_the_producers_key_order(case_name: str) -> None:
    """Key ORDER is fixture content, because the consumer depends on it.

    ``providedKeysDiffer`` walks ``Object.entries`` and, before this was
    caught, returned at the first differing key — so WHERE a summarized key
    sits among its siblings decided whether it was examined at all. On the
    wire ``plugin`` precedes ``options`` on a source and an output; sorted, it
    follows them. A sorted fixture therefore exercises a path the live payload
    never takes, and no equality assertion notices, because ``==`` on dicts
    ignores order.

    This is the assertion the ordinary drift test cannot make:
    ``test_recorded_redaction_matches_the_live_redactor`` compares parsed
    dicts and would stay green against a re-sorted fixture.
    """
    case = frontend.fixture_cases()[case_name]
    actual = redact_tool_call_arguments(case["tool"], case["arguments"], telemetry=NoopRedactionTelemetry())

    assert _key_order(json.loads(json.dumps(actual))) == _key_order(case["redacted"]), (
        f"Key-order drift for fixture case '{case_name}'. The generator must NOT "
        f"sort keys — the frontend's short-circuit depends on the producer's own "
        f"order. {frontend.REGENERATE_HINT}"
    )


def test_projected_tools_all_exist_in_the_manifest() -> None:
    """Every frontend projector must name a live producer tool."""
    frontend.census_frontend_wire()  # Exact projected/case references checked by shared authority.


def test_every_summarized_argument_is_recorded_as_a_string() -> None:
    """The consumer-facing fact this fixture exists to pin.

    `patch` on the three patch_*_options tools and on set_metadata is a
    STRING after redaction, never a mapping. A frontend reader that treats it
    as a mapping is dead code, and this is the assertion that says so in the
    language that can see the producer.

    `patch` may also be ABSENT — set_metadata called with no arguments
    redacts to ``{}``. Absent is a third state, distinct from both a mapping
    and a summary string, and a decoder that only handles strings has to
    survive it. What is asserted here is the narrow fact that matters: when
    `patch` is present it is a string, never a mapping.
    """
    summarized_patch_tools = {
        "patch_source_options",
        "patch_node_options",
        "patch_output_options",
        "set_metadata",
    }
    saw_absent_patch = False
    for case_name, case in frontend.fixture_cases().items():
        if case["tool"] not in summarized_patch_tools:
            continue
        if "patch" not in case["redacted"]:
            saw_absent_patch = True
            continue
        patch = case["redacted"]["patch"]
        assert isinstance(patch, str), (
            f"Fixture case '{case_name}' records a non-string patch ({type(patch).__name__}). {frontend.REGENERATE_HINT}"
        )

    # Keep the absent-patch case in the corpus deliberately: it is the only
    # one that exercises `args.patch === undefined` on the consumer side.
    assert saw_absent_patch, f"Fixture no longer records a case with an absent `patch`. {frontend.REGENERATE_HINT}"


def test_shared_frontend_missing_fixture_is_an_extraction_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(frontend, "FIXTURE_PATH", tmp_path / "missing.json")
    with pytest.raises(frontend.FrontendCensusError, match=r"missing\.json"):
        frontend.census_frontend_wire()


@pytest.mark.parametrize("mutation", ["duplicate_projected", "unknown_projected", "unknown_case", "duplicate_case", "missing_inventory"])
def test_shared_frontend_rejects_invalid_inventory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mutation: str) -> None:
    fixture = frontend.load_fixture()
    if mutation == "duplicate_projected":
        name = fixture["projected_tools"][0]
        fixture["projected_tools"].append(name)
        expected = name
    elif mutation == "unknown_projected":
        fixture["projected_tools"].append("not_a_producer")
        expected = "not_a_producer"
    elif mutation == "unknown_case":
        name = next(iter(fixture["cases"]))
        fixture["cases"][name]["tool"] = "not_a_case_producer"
        expected = name
    elif mutation == "missing_inventory":
        del fixture["projected_tools"]
        expected = "missing projected_tools"
    else:
        expected = "duplicate_case"
    payload = json.dumps(fixture)
    if mutation == "duplicate_case":
        payload = payload.replace('"cases": {', '"cases": {"duplicate_case": {}, "duplicate_case": {},', 1)
    path = tmp_path / "fixture.json"
    path.write_text(payload)
    monkeypatch.setattr(frontend, "FIXTURE_PATH", path)
    with pytest.raises(frontend.FrontendCensusError, match=expected):
        frontend.census_frontend_wire()


def test_shared_frontend_reports_summarized_fixture_loss_and_restoration(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    original = frontend.load_fixture()
    baseline = frontend.census_frontend_wire()
    name = next(name for name, row in baseline.items() if row.fixture_required and row.fixture_cases)
    path = tmp_path / "fixture.json"
    path.write_text(json.dumps(original))
    monkeypatch.setattr(frontend, "FIXTURE_PATH", path)
    assert not frontend.census_frontend_wire()[name].missing_fixture
    original_cases = original["cases"]
    original["cases"] = {case_name: case for case_name, case in original_cases.items() if case["tool"] != name}
    path.write_text(json.dumps(original))
    row = frontend.census_frontend_wire()[name]
    assert row.projected and row.summarizes_argument and row.missing_fixture
    assert row.fixture_cases == frozenset()
    with pytest.raises(AssertionError, match=name):
        test_fixture_records_every_projected_tool_whose_arguments_are_summarized()
    original["cases"] = original_cases
    path.write_text(json.dumps(original))
    assert not frontend.census_frontend_wire()[name].missing_fixture
    test_fixture_records_every_projected_tool_whose_arguments_are_summarized()
